import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 6,
    title: 'Belajar Bangun Ruang di Masjid Al-Akbar Surabaya',
    subtitle: 'Etnomatematika Bangun Ruang',
    location: 'Masjid Al-Akbar Surabaya',
    classLevel: 'II / Fase A Semester 1',
    cover: '/comics/komik-6/cover.png',
    thumbnail: '/comics/komik-6/thumbnail.png',
    learningTargets: [
      'Mengenal kubus, balok, tabung, kerucut, dan setengah bola',
      'Menganalisis sisi, rusuk, titik sudut, dan titik puncak pada bangun ruang',
      'Menghubungkan bangun ruang dengan arsitektur Masjid Al-Akbar Surabaya',
      'Membuat bangun ruang berdasarkan ciri-ciri yang telah diamati',
    ],
    synopsis:
      'Bu Syarla dan siswa kelas II belajar bangun ruang di Masjid Al-Akbar Surabaya. Mereka mengamati menara, kubah, ruang utama, dan tempat duduk wudu untuk mengenali tabung, kerucut, setengah bola, balok, dan kubus.',
  },
  learningObjects: [
    {
      id: 'komik6-menara-tabung',
      title: 'Menara Masjid',
      description: 'Menara Masjid Al-Akbar diamati sebagai bangun ruang tabung.',
      page: 11,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Perhatikan menara. Apa bentuk sisi atas dan sisi bawahnya? Berapa sisi tabung yang disebutkan Bu Syarla?',
      aiPrompt: 'Bantu siswa kelas II mengamati menara Masjid Al-Akbar sebagai tabung. Ajak siswa mencari sisi atas berbentuk lingkaran, sisi alas, sisi selimut, dan dua rusuk. Beri petunjuk bertahap, jangan langsung memberi jawaban aktivitas.',
      question: 'Bangun ruang apa yang paling mirip dengan menara masjid?', answer: 'Tabung',
      feedback: 'Benar. Menara diamati seperti tabung, dengan sisi atas, sisi alas, sisi selimut, dan dua rusuk.',
      characteristics: ['3 sisi', '2 rusuk', 'Sisi atas dan alas berbentuk lingkaran', 'Memiliki sisi selimut'], shapeKey: 'tabung', shapeName: 'Tabung',
    },
    {
      id: 'komik6-kubah-kerucut', title: 'Bagian Atas Kubah', description: 'Bagian atas kubah utama diamati sebagai bangun ruang kerucut.', page: 12,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Amati bagian atas kubah. Di mana letak titik puncaknya? Apakah kerucut memiliki titik sudut?',
      aiPrompt: 'Bantu siswa mengenali bagian atas kubah sebagai kerucut. Ajak siswa mengamati satu titik puncak, satu rusuk, dan dua sisi. Jelaskan perlahan bahwa titik puncak berbeda dari titik sudut. Jangan membocorkan jawaban aktivitas.',
      question: 'Bangun ruang apa yang paling mirip dengan bagian atas kubah?', answer: 'Kerucut',
      feedback: 'Bagus. Bagian atas kubah seperti kerucut karena memiliki titik puncak, dua sisi, dan satu rusuk.',
      characteristics: ['2 sisi', '1 rusuk', 'Memiliki titik puncak', 'Tidak memiliki titik sudut'], shapeKey: 'kerucut', shapeName: 'Kerucut',
    },
    {
      id: 'komik6-kubah-setengah-bola', title: 'Bagian Bawah Kubah', description: 'Bagian bawah kubah diamati seperti setengah bola yang tertutup.', page: 13,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Bagian bawah kubah tampak melengkung seperti apa? Apakah bagian ini memiliki titik sudut?',
      aiPrompt: 'Bantu siswa membedakan setengah bola dari kerucut pada kubah. Ajak siswa memperhatikan sisi lengkung dan bagian yang tertutup. Gunakan bahasa sederhana dan petunjuk, bukan jawaban langsung.',
      question: 'Bangun ruang apa yang paling mirip dengan bagian bawah kubah?', answer: 'Setengah bola',
      feedback: 'Benar. Bagian bawah kubah tampak seperti setengah bola yang tertutup dan tidak memiliki titik sudut.',
      characteristics: ['Bagian dari bola', 'Memiliki sisi lengkung', 'Memiliki bagian yang tertutup', 'Tidak memiliki titik sudut'], shapeKey: 'setengah-bola', shapeName: 'Setengah bola',
    },
    {
      id: 'komik6-ruang-utama-balok', title: 'Ruang Utama Masjid', description: 'Ruang utama masjid diamati sebagai bangun ruang balok.', page: 13,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Perhatikan ruang utama. Apakah sisi-sisinya tampak seperti persegi panjang? Berapa sisi, rusuk, dan titik sudut balok?',
      aiPrompt: 'Bimbing siswa mengamati ruang utama sebagai balok. Minta siswa menghitung enam sisi berbentuk persegi panjang, dua belas rusuk, dan delapan titik sudut. Beri kesempatan siswa mencoba sebelum menjelaskan.',
      question: 'Bangun ruang apa yang paling cocok untuk ruang utama masjid?', answer: 'Balok',
      feedback: 'Tepat. Ruang utama seperti balok: memiliki 6 sisi berbentuk persegi panjang, 12 rusuk, dan 8 titik sudut.',
      characteristics: ['6 sisi', '12 rusuk', '8 titik sudut', 'Sisinya berbentuk persegi panjang'], shapeKey: 'balok', shapeName: 'Balok',
    },
    {
      id: 'komik6-tempat-duduk-wudu-kubus', title: 'Tempat Duduk Wudu', description: 'Tempat duduk wudu berwarna cokelat diamati sebagai bangun ruang kubus.', page: 14,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Apakah semua sisi tempat duduk wudu berbentuk persegi? Berapa rusuk dan titik sudutnya?',
      aiPrompt: 'Bantu siswa mengenali tempat duduk wudu sebagai kubus. Ajak siswa mengamati enam sisi persegi, dua belas rusuk sama panjang, dan delapan titik sudut. Beri petunjuk bertahap tanpa langsung memberi jawaban.',
      question: 'Bangun ruang apa yang paling mirip dengan tempat duduk wudu?', answer: 'Kubus',
      feedback: 'Hebat. Tempat duduk wudu seperti kubus karena memiliki 6 sisi persegi, 12 rusuk sama panjang, dan 8 titik sudut.',
      characteristics: ['6 sisi berbentuk persegi', '12 rusuk sama panjang', '8 titik sudut', 'Semua sisinya persegi'], shapeKey: 'kubus', shapeName: 'Kubus',
    },
  ],
  qrCode: [],
  model3D: [],
  aiPrompt: {
    navigation: 'Bimbing siswa kelas II mengamati bangun ruang pada arsitektur Masjid Al-Akbar Surabaya. Ajak mereka memperhatikan bentuk dan ciri, lalu menghubungkannya dengan tabung, kerucut, setengah bola, balok, atau kubus.',
    objectTutor: 'Jelaskan objek Masjid Al-Akbar dengan bahasa sederhana. Berikan petunjuk bertahap tentang sisi, rusuk, titik sudut, atau titik puncak. Jangan memberi jawaban aktivitas sebelum siswa mencoba.',
    application: 'Hubungkan lima bangun ruang yang diamati di Masjid Al-Akbar dengan benda dekat siswa. Tetap gunakan konsep kubus, balok, tabung, kerucut, dan setengah bola.',
    argumentation: 'Bantu siswa menjelaskan apa yang dilihat, bangun ruang yang dipilih, dan ciri yang menjadi alasan. Tanggapi secara bertahap dan ramah; jangan hanya mengatakan salah atau memberikan jawaban lengkap.',
    resolution: 'Bimbing siswa menyelesaikan misi klasifikasi bangun ruang dari Masjid Al-Akbar. Arahkan siswa memakai jumlah sisi, rusuk, titik sudut, atau titik puncak yang disebut dalam komik.',
    introspection: 'Ajak siswa merefleksikan bangun ruang yang dipelajari di Masjid Al-Akbar, ciri yang paling dipahami, bagian yang masih sulit, dan benda yang dapat diamati di sekitar.',
  },
  identification: {
    questions: [
      {
        id: 'komik6-identifikasi-bangun-ruang',
        question: 'Perhatikan bangunan Masjid Al-Akbar. Bangun ruang apa saja yang dapat kamu temukan?',
        image: '',
        imageAlt: 'Bangunan Masjid Al-Akbar dengan menara, kubah, ruang utama, dan tempat duduk wudu.',
        options: [
          { text: 'Kubus', correct: true, example: 'Tempat duduk/tempat wudhu', properties: ['6 sisi berbentuk persegi', '12 rusuk sama panjang', '8 titik sudut'], feedback: 'Benar! Tempat duduk wudu menyerupai kubus.' },
          { text: 'Balok', correct: true, example: 'Bagian utama/interior masjid', properties: ['6 sisi berbentuk persegi panjang', '12 rusuk', '8 titik sudut'], feedback: 'Benar! Bagian utama masjid memiliki bentuk yang menyerupai balok.' },
          { text: 'Tabung', correct: true, example: 'Menara masjid', properties: ['3 sisi', '2 rusuk', '2 sisi berbentuk lingkaran', '1 sisi selimut'], feedback: 'Benar! Menara Masjid Al-Akbar menyerupai tabung.' },
          { text: 'Kerucut', correct: true, example: 'Bagian atas kubah', properties: ['2 sisi', '1 rusuk', '1 titik puncak', 'Tidak memiliki titik sudut'], feedback: 'Benar! Bagian atas kubah menyerupai kerucut.' },
          { text: 'Setengah bola', correct: true, example: 'Bagian bawah kubah', properties: ['Sisi lengkung', 'Bagian bola yang tertutup', 'Tidak memiliki titik sudut'], feedback: 'Benar! Bagian bawah kubah menyerupai setengah bola.' },
        ],
        explanation: 'Pilih lima bangun ruang yang ditemukan pada objek Masjid Al-Akbar. Amati hubungan setiap bangun dengan menara, kubah, ruang utama, dan tempat duduk wudu.',
      },
    ],
    feedback: {
      complete: 'Hebat! Kamu berhasil mengenali bangun ruang pada arsitektur Masjid Al-Akbar.',
      partial: 'Sudah bagus. Amati lagi ciri sisi, rusuk, dan titik sudut pada bangun yang belum tepat.',
      incomplete: 'Coba kembali ke objek dalam komik. Perhatikan bentuknya sebelum memilih jawaban.',
    },
  },
  application: {
    title: 'Bangun Ruang di Sekitarmu',
    intro: 'Setelah mengamati Masjid Al-Akbar, carilah benda di sekitar yang memiliki bentuk bangun ruang serupa.',
    prompt: 'Pilih bangun ruang yang paling sesuai dan jelaskan ciri yang membuatmu yakin.',
    context: 'Benda di rumah dan sekolah dapat membantu kita mengingat bentuk kubus, balok, tabung, kerucut, dan setengah bola.',
    correctAnswer: 'Kubus',
    images: [],
    options: [
      { value: 'Kubus', label: 'Kubus' }, { value: 'Balok', label: 'Balok' }, { value: 'Tabung', label: 'Tabung' },
      { value: 'Kerucut', label: 'Kerucut' }, { value: 'Setengah bola', label: 'Setengah bola' },
    ],
  },
  argumentation: {
    questions: [
      { id: 'komik6-arg-1', title: 'Menara Masjid', templePart: 'menara', question: 'Menurutmu, mengapa menara Masjid Al-Akbar menyerupai tabung?', photoSrc: '/comics/generated/komik-6/page-11.png', image: '/comics/generated/komik-6/page-11.png', photoAlt: 'Menara Masjid Al-Akbar.', shape: 'Tabung', shapeName: 'Tabung', shapeKey: 'tabung', shapeSrc: '', aiContext: 'Bantu siswa melihat sisi atas dan bawah berbentuk lingkaran, sisi selimut, dan 2 rusuk.', feedback: 'Menara menyerupai tabung karena memiliki sisi atas dan sisi bawah berbentuk lingkaran, serta sisi selimut. Tabung juga memiliki 2 rusuk.', argumentationAnswer: 'Menara menyerupai tabung karena memiliki sisi atas dan sisi bawah berbentuk lingkaran, serta sisi selimut. Tabung juga memiliki 2 rusuk.', argumentationHint: 'Coba perhatikan sisi berbentuk lingkaran dan sisi selimut pada tabung.', highlightColor: 'border-cyan-500', characteristics: [{ id: 'a', label: 'Memiliki dua sisi berbentuk lingkaran', correct: true }, { id: 'b', label: 'Memiliki sisi selimut', correct: true }, { id: 'c', label: 'Memiliki 2 rusuk', correct: true }, { id: 'd', label: 'Memiliki 8 titik sudut', correct: false }, { id: 'e', label: 'Memiliki 6 sisi berbentuk persegi', correct: false }] },
      { id: 'komik6-arg-2', title: 'Bagian Atas Kubah', templePart: 'bagian atas kubah', question: 'Bagian atas kubah menyerupai kerucut. Mengapa?', photoSrc: '/comics/generated/komik-6/page-12.png', image: '/comics/generated/komik-6/page-12.png', photoAlt: 'Bagian atas kubah Masjid Al-Akbar.', shape: 'Kerucut', shapeName: 'Kerucut', shapeKey: 'kerucut', shapeSrc: '', aiContext: 'Bantu siswa mencari 2 sisi, 1 rusuk, dan titik puncak.', feedback: 'Benar! Bagian atas kubah menyerupai kerucut karena memiliki 2 sisi, 1 rusuk, dan titik puncak.', argumentationAnswer: 'Bagian atas kubah menyerupai kerucut karena memiliki 2 sisi, 1 rusuk, dan titik puncak.', argumentationHint: 'Perhatikan bagian kubah yang mengarah ke satu titik puncak.', highlightColor: 'border-amber-500', characteristics: [{ id: 'a', label: 'Memiliki 2 sisi', correct: true }, { id: 'b', label: 'Memiliki 1 rusuk', correct: true }, { id: 'c', label: 'Memiliki titik puncak', correct: true }, { id: 'd', label: 'Memiliki 8 titik sudut', correct: false }, { id: 'e', label: 'Memiliki 6 sisi persegi panjang', correct: false }] },
      { id: 'komik6-arg-3', title: 'Bagian Bawah Kubah', templePart: 'bagian bawah kubah', question: 'Bagian bawah kubah menyerupai setengah bola. Ciri apa yang mendukung jawabanmu?', photoSrc: '/comics/generated/komik-6/page-12.png', image: '/comics/generated/komik-6/page-12.png', photoAlt: 'Bagian bawah kubah Masjid Al-Akbar.', shape: 'Setengah bola', shapeName: 'Setengah bola', shapeKey: 'setengah-bola', shapeSrc: '', aiContext: 'Bantu siswa memperhatikan sisi lengkung dan tidak adanya titik sudut.', feedback: 'Benar! Bagian bawah kubah menyerupai setengah bola karena memiliki sisi lengkung dan tidak memiliki titik sudut.', argumentationAnswer: 'Bagian bawah kubah menyerupai setengah bola karena memiliki sisi lengkung dan tidak memiliki titik sudut.', argumentationHint: 'Cari ciri bentuk yang melengkung dan tidak memiliki titik sudut.', highlightColor: 'border-sky-500', characteristics: [{ id: 'a', label: 'Memiliki sisi lengkung', correct: true }, { id: 'b', label: 'Tidak memiliki titik sudut', correct: true }, { id: 'c', label: 'Memiliki 12 rusuk', correct: false }, { id: 'd', label: 'Memiliki 8 titik sudut', correct: false }, { id: 'e', label: 'Memiliki 6 sisi persegi', correct: false }] },
      { id: 'komik6-arg-4', title: 'Ruang Utama', templePart: 'bagian utama masjid', question: 'Bagian utama masjid menyerupai balok. Mengapa?', photoSrc: '/comics/generated/komik-6/page-13.png', image: '/comics/generated/komik-6/page-13.png', photoAlt: 'Bagian utama Masjid Al-Akbar.', shape: 'Balok', shapeName: 'Balok', shapeKey: 'balok', shapeSrc: '', aiContext: 'Bantu siswa melihat 6 sisi berbentuk persegi panjang, 12 rusuk, dan 8 titik sudut.', feedback: 'Benar! Bagian utama masjid menyerupai balok karena memiliki 6 sisi berbentuk persegi panjang, 12 rusuk, dan 8 titik sudut.', argumentationAnswer: 'Bagian utama masjid menyerupai balok karena memiliki 6 sisi berbentuk persegi panjang, 12 rusuk, dan 8 titik sudut.', argumentationHint: 'Perhatikan jumlah sisi, rusuk, dan titik sudut balok.', highlightColor: 'border-emerald-500', characteristics: [{ id: 'a', label: 'Memiliki 6 sisi', correct: true }, { id: 'b', label: 'Sisinya berbentuk persegi panjang', correct: true }, { id: 'c', label: 'Memiliki 12 rusuk', correct: true }, { id: 'd', label: 'Memiliki 8 titik sudut', correct: true }, { id: 'e', label: 'Memiliki sisi lengkung', correct: false }] },
      { id: 'komik6-arg-5', title: 'Tempat Duduk Wudu', templePart: 'tempat duduk wudu', question: 'Tempat duduk wudu menyerupai kubus. Apa alasannya?', photoSrc: '/comics/generated/komik-6/page-14.png', image: '/comics/generated/komik-6/page-14.png', photoAlt: 'Tempat duduk wudu di ruang wudu.', shape: 'Kubus', shapeName: 'Kubus', shapeKey: 'kubus', shapeSrc: '', aiContext: 'Bantu siswa mengamati 6 sisi berbentuk persegi, 12 rusuk sama panjang, dan 8 titik sudut.', feedback: 'Benar! Tempat duduk wudu menyerupai kubus karena memiliki 6 sisi berbentuk persegi, 12 rusuk yang sama panjang, dan 8 titik sudut.', argumentationAnswer: 'Tempat duduk wudu menyerupai kubus karena memiliki 6 sisi berbentuk persegi, 12 rusuk yang sama panjang, dan 8 titik sudut.', argumentationHint: 'Perhatikan sisi persegi dan rusuk yang sama panjang pada kubus.', highlightColor: 'border-violet-500', characteristics: [{ id: 'a', label: 'Memiliki 6 sisi berbentuk persegi', correct: true }, { id: 'b', label: 'Memiliki 12 rusuk yang sama panjang', correct: true }, { id: 'c', label: 'Memiliki 8 titik sudut', correct: true }, { id: 'd', label: 'Memiliki sisi lengkung', correct: false }, { id: 'e', label: 'Memiliki titik puncak', correct: false }] },
    ],
  },
  resolution: {
    missions: [
      { id: 1, title: 'Misi Menara', part: 'menara', shape: 'Tabung', prompt: 'Pilih ciri yang sesuai dengan menara yang diamati.', options: [{ key: 'a', label: 'Memiliki sisi atas dan alas berbentuk lingkaran' }, { key: 'b', label: 'Memiliki semua sisi berbentuk persegi' }], correctKey: 'a', answer: 'Tabung memiliki sisi atas dan alas berbentuk lingkaran.', formula: '3 sisi dan 2 rusuk', explanation: 'Ciri itu sesuai dengan tabung yang dijelaskan pada halaman pengamatan menara.', aiHint: 'Cari ciri menara yang berkaitan dengan lingkaran.', context: 'Menara Masjid Al-Akbar', accent: 'cyan', illustration: '' },
      { id: 2, title: 'Misi Kubah Atas', part: 'bagian atas kubah', shape: 'Kerucut', prompt: 'Ciri apa yang membantu mengenali bagian atas kubah sebagai kerucut?', options: [{ key: 'a', label: 'Memiliki titik puncak' }, { key: 'b', label: 'Memiliki delapan titik sudut' }], correctKey: 'a', answer: 'Kerucut memiliki titik puncak.', formula: '2 sisi dan 1 rusuk', explanation: 'Bagian atas kubah memiliki bentuk yang mengarah ke satu titik puncak.', aiHint: 'Perhatikan bagian kubah yang meruncing ke atas.', context: 'Kubah utama Masjid Al-Akbar', accent: 'amber', illustration: '' },
      { id: 3, title: 'Misi Ruang Utama', part: 'ruang utama', shape: 'Balok', prompt: 'Berapa sisi yang dimiliki balok menurut penjelasan dalam komik?', options: [{ key: 'a', label: '6 sisi' }, { key: 'b', label: '3 sisi' }], correctKey: 'a', answer: 'Balok memiliki 6 sisi.', formula: '6 sisi, 12 rusuk, dan 8 titik sudut', explanation: 'Ruang utama diamati sebagai balok dengan sisi berbentuk persegi panjang.', aiHint: 'Ingat tiga angka ciri balok yang disebut Bu Syarla.', context: 'Ruang utama masjid', accent: 'emerald', illustration: '' },
      { id: 4, title: 'Misi Tempat Duduk Wudu', part: 'tempat duduk wudu', shape: 'Kubus', prompt: 'Ciri mana yang paling sesuai dengan kubus?', options: [{ key: 'a', label: '6 sisi berbentuk persegi dan 12 rusuk sama panjang' }, { key: 'b', label: 'Memiliki sisi selimut dan titik puncak' }], correctKey: 'a', answer: 'Kubus memiliki 6 sisi persegi dan 12 rusuk sama panjang.', formula: '6 sisi, 12 rusuk, dan 8 titik sudut', explanation: 'Tempat duduk wudu diamati sebagai kubus.', aiHint: 'Bandingkan sisi persegi kubus dengan sisi selimut tabung.', context: 'Ruang wudu masjid', accent: 'violet', illustration: '' },
      { id: 5, title: 'Misi Kubah Bawah', part: 'bagian bawah kubah', shape: 'Setengah bola', prompt: 'Mengapa bagian bawah kubah bukan kerucut?', options: [{ key: 'a', label: 'Karena bentuknya melengkung seperti sebagian bola' }, { key: 'b', label: 'Karena memiliki titik puncak' }], correctKey: 'a', answer: 'Bagian bawah kubah melengkung seperti setengah bola dan tidak memiliki titik sudut.', formula: 'Sisi lengkung dan bagian tertutup', explanation: 'Perhatikan perbedaan bentuk melengkung dengan bagian atas kubah yang meruncing.', aiHint: 'Cari bentuk yang tidak memiliki titik puncak.', context: 'Bagian bawah kubah masjid', accent: 'sky', illustration: '' },
    ],
  },
  introspection: {
    checklist: ['Aku dapat menyebutkan kubus, balok, tabung, kerucut, dan setengah bola.', 'Aku dapat menyebutkan sisi, rusuk, titik sudut, atau titik puncak pada bangun ruang.', 'Aku dapat menghubungkan bangun ruang dengan bagian Masjid Al-Akbar.', 'Aku dapat menjelaskan alasan saat memilih sebuah bangun ruang.'],
    completionMessage: 'Hebat! Kamu sudah belajar mengenali bangun ruang dari arsitektur Masjid Al-Akbar Surabaya.',
    nextPrompt: 'Amati satu benda di sekitarmu. Bangun ruang apa yang paling mirip dan apa cirinya?',
  },
  report: {
    summary: 'Pada Komik 6, siswa belajar bangun ruang melalui pengamatan arsitektur Masjid Al-Akbar Surabaya. Siswa mengenali tabung pada menara, kerucut dan setengah bola pada kubah, balok pada ruang utama, serta kubus pada tempat duduk wudu.',
    learnedShapes: ['Tabung', 'Kerucut', 'Setengah bola', 'Balok', 'Kubus'],
  },
};
