import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 6,
    title: 'Belajar Bangun Ruang di Masjid Al-Akbar Surabaya',
    subtitle: 'Etnomatematika Bangun Ruang',
    location: 'Masjid Al-Akbar Surabaya',
    classLevel: 'II / Fase A Semester 1',
    cover: '/comics/komik-6/cover.png',
    thumbnail: '/comics/komik-6/thumbnail.png',
    learningTargets: [
      'Mengenal kubus, balok, tabung, kerucut, dan setengah bola',
      'Menganalisis sisi, rusuk, titik sudut, dan titik puncak pada bangun ruang',
      'Menghubungkan bangun ruang dengan arsitektur Masjid Al-Akbar Surabaya',
      'Membuat bangun ruang berdasarkan ciri-ciri yang telah diamati',
    ],
    synopsis:
      'Bu Syarla dan siswa kelas II belajar bangun ruang di Masjid Al-Akbar Surabaya. Mereka mengamati menara, kubah, ruang utama, dan tempat duduk wudu untuk mengenali tabung, kerucut, setengah bola, balok, dan kubus.',
  },
  learningObjects: [
    {
      id: 'komik6-menara-tabung',
      title: 'Menara Masjid',
      description: 'Menara Masjid Al-Akbar diamati sebagai bangun ruang tabung.',
      page: 11,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Perhatikan menara. Apa bentuk sisi atas dan sisi bawahnya? Berapa sisi tabung yang disebutkan Bu Syarla?',
      aiPrompt: 'Bantu siswa kelas II mengamati menara Masjid Al-Akbar sebagai tabung. Ajak siswa mencari sisi atas berbentuk lingkaran, sisi alas, sisi selimut, dan dua rusuk. Beri petunjuk bertahap, jangan langsung memberi jawaban aktivitas.',
      question: 'Bangun ruang apa yang paling mirip dengan menara masjid?', answer: 'Tabung',
      feedback: 'Benar. Menara diamati seperti tabung, dengan sisi atas, sisi alas, sisi selimut, dan dua rusuk.',
      characteristics: ['3 sisi', '2 rusuk', 'Sisi atas dan alas berbentuk lingkaran', 'Memiliki sisi selimut'], shapeKey: 'tabung', shapeName: 'Tabung',
    },
    {
      id: 'komik6-kubah-kerucut', title: 'Bagian Atas Kubah', description: 'Bagian atas kubah utama diamati sebagai bangun ruang kerucut.', page: 12,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Amati bagian atas kubah. Di mana letak titik puncaknya? Apakah kerucut memiliki titik sudut?',
      aiPrompt: 'Bantu siswa mengenali bagian atas kubah sebagai kerucut. Ajak siswa mengamati satu titik puncak, satu rusuk, dan dua sisi. Jelaskan perlahan bahwa titik puncak berbeda dari titik sudut. Jangan membocorkan jawaban aktivitas.',
      question: 'Bangun ruang apa yang paling mirip dengan bagian atas kubah?', answer: 'Kerucut',
      feedback: 'Bagus. Bagian atas kubah seperti kerucut karena memiliki titik puncak, dua sisi, dan satu rusuk.',
      characteristics: ['2 sisi', '1 rusuk', 'Memiliki titik puncak', 'Tidak memiliki titik sudut'], shapeKey: 'kerucut', shapeName: 'Kerucut',
    },
    {
      id: 'komik6-kubah-setengah-bola', title: 'Bagian Bawah Kubah', description: 'Bagian bawah kubah diamati seperti setengah bola yang tertutup.', page: 13,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Bagian bawah kubah tampak melengkung seperti apa? Apakah bagian ini memiliki titik sudut?',
      aiPrompt: 'Bantu siswa membedakan setengah bola dari kerucut pada kubah. Ajak siswa memperhatikan sisi lengkung dan bagian yang tertutup. Gunakan bahasa sederhana dan petunjuk, bukan jawaban langsung.',
      question: 'Bangun ruang apa yang paling mirip dengan bagian bawah kubah?', answer: 'Setengah bola',
      feedback: 'Benar. Bagian bawah kubah tampak seperti setengah bola yang tertutup dan tidak memiliki titik sudut.',
      characteristics: ['Bagian dari bola', 'Memiliki sisi lengkung', 'Memiliki bagian yang tertutup', 'Tidak memiliki titik sudut'], shapeKey: 'setengah-bola', shapeName: 'Setengah bola',
    },
    {
      id: 'komik6-ruang-utama-balok', title: 'Ruang Utama Masjid', description: 'Ruang utama masjid diamati sebagai bangun ruang balok.', page: 13,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Perhatikan ruang utama. Apakah sisi-sisinya tampak seperti persegi panjang? Berapa sisi, rusuk, dan titik sudut balok?',
      aiPrompt: 'Bimbing siswa mengamati ruang utama sebagai balok. Minta siswa menghitung enam sisi berbentuk persegi panjang, dua belas rusuk, dan delapan titik sudut. Beri kesempatan siswa mencoba sebelum menjelaskan.',
      question: 'Bangun ruang apa yang paling cocok untuk ruang utama masjid?', answer: 'Balok',
      feedback: 'Tepat. Ruang utama seperti balok: memiliki 6 sisi berbentuk persegi panjang, 12 rusuk, dan 8 titik sudut.',
      characteristics: ['6 sisi', '12 rusuk', '8 titik sudut', 'Sisinya berbentuk persegi panjang'], shapeKey: 'balok', shapeName: 'Balok',
    },
    {
      id: 'komik6-tempat-duduk-wudu-kubus', title: 'Tempat Duduk Wudu', description: 'Tempat duduk wudu berwarna cokelat diamati sebagai bangun ruang kubus.', page: 14,
      qrImage: '', navImage: '', objectImage: '', image: '', modelUrl: '', embedUrl: '', viewerType: 'embed', provider: '',
      observationQuestion: 'Apakah semua sisi tempat duduk wudu berbentuk persegi? Berapa rusuk dan titik sudutnya?',
      aiPrompt: 'Bantu siswa mengenali tempat duduk wudu sebagai kubus. Ajak siswa mengamati enam sisi persegi, dua belas rusuk sama panjang, dan delapan titik sudut. Beri petunjuk bertahap tanpa langsung memberi jawaban.',
      question: 'Bangun ruang apa yang paling mirip dengan tempat duduk wudu?', answer: 'Kubus',
      feedback: 'Hebat. Tempat duduk wudu seperti kubus karena memiliki 6 sisi persegi, 12 rusuk sama panjang, dan 8 titik sudut.',
      characteristics: ['6 sisi berbentuk persegi', '12 rusuk sama panjang', '8 titik sudut', 'Semua sisinya persegi'], shapeKey: 'kubus', shapeName: 'Kubus',
    },
  ],
  qrCode: [],
  model3D: [],
  aiPrompt: {
    navigation: 'Bimbing siswa kelas II mengamati bangun ruang pada arsitektur Masjid Al-Akbar Surabaya. Ajak mereka memperhatikan bentuk dan ciri, lalu menghubungkannya dengan tabung, kerucut, setengah bola, balok, atau kubus.',
    objectTutor: 'Jelaskan objek Masjid Al-Akbar dengan bahasa sederhana. Berikan petunjuk bertahap tentang sisi, rusuk, titik sudut, atau titik puncak. Jangan memberi jawaban aktivitas sebelum siswa mencoba.',
    application: 'Hubungkan lima bangun ruang yang diamati di Masjid Al-Akbar dengan benda dekat siswa. Tetap gunakan konsep kubus, balok, tabung, kerucut, dan setengah bola.',
    argumentation: 'Bantu siswa menjelaskan apa yang dilihat, bangun ruang yang dipilih, dan ciri yang menjadi alasan. Tanggapi secara bertahap dan ramah; jangan hanya mengatakan salah atau memberikan jawaban lengkap.',
    resolution: 'Bimbing siswa menyelesaikan misi klasifikasi bangun ruang dari Masjid Al-Akbar. Arahkan siswa memakai jumlah sisi, rusuk, titik sudut, atau titik puncak yang disebut dalam komik.',
    introspection: 'Ajak siswa merefleksikan bangun ruang yang dipelajari di Masjid Al-Akbar, ciri yang paling dipahami, bagian yang masih sulit, dan benda yang dapat diamati di sekitar.',
  },
  identification: {
    questions: [
      { id: 'komik6-ident-1', question: 'Menara Masjid Al-Akbar paling mirip dengan bangun ruang apa?', image: '', imageAlt: 'Menara Masjid Al-Akbar yang diamati sebagai tabung.', options: [{ text: 'Tabung', correct: true }, { text: 'Kubus', correct: false }, { text: 'Kerucut', correct: false }, { text: 'Balok', correct: false }], explanation: 'Menara diamati seperti tabung. Tabung memiliki sisi atas dan alas berbentuk lingkaran serta sisi selimut.' },
      { id: 'komik6-ident-2', question: 'Bagian atas kubah paling mirip dengan bangun ruang apa?', image: '', imageAlt: 'Bagian atas kubah Masjid Al-Akbar yang diamati sebagai kerucut.', options: [{ text: 'Kerucut', correct: true }, { text: 'Bola', correct: false }, { text: 'Balok', correct: false }, { text: 'Kubus', correct: false }], explanation: 'Bagian atas kubah seperti kerucut karena memiliki titik puncak.' },
      { id: 'komik6-ident-3', question: 'Bagian bawah kubah diamati seperti bangun ruang apa?', image: '', imageAlt: 'Bagian bawah kubah yang diamati sebagai setengah bola.', options: [{ text: 'Setengah bola', correct: true }, { text: 'Tabung', correct: false }, { text: 'Kubus', correct: false }, { text: 'Kerucut', correct: false }], explanation: 'Bagian bawah kubah tampak seperti setengah bola, memiliki sisi lengkung, dan tidak memiliki titik sudut.' },
      { id: 'komik6-ident-4', question: 'Ruang utama masjid paling cocok disebut bangun ruang apa?', image: '', imageAlt: 'Ruang utama Masjid Al-Akbar yang diamati sebagai balok.', options: [{ text: 'Balok', correct: true }, { text: 'Kerucut', correct: false }, { text: 'Tabung', correct: false }, { text: 'Bola', correct: false }], explanation: 'Ruang utama seperti balok karena memiliki enam sisi berbentuk persegi panjang.' },
      { id: 'komik6-ident-5', question: 'Tempat duduk wudu berwarna cokelat paling mirip dengan bangun ruang apa?', image: '', imageAlt: 'Tempat duduk wudu yang diamati sebagai kubus.', options: [{ text: 'Kubus', correct: true }, { text: 'Balok', correct: false }, { text: 'Tabung', correct: false }, { text: 'Setengah bola', correct: false }], explanation: 'Tempat duduk wudu diamati sebagai kubus dengan enam sisi berbentuk persegi.' },
    ],
    feedback: {
      complete: 'Hebat! Kamu berhasil mengenali bangun ruang pada arsitektur Masjid Al-Akbar.',
      partial: 'Sudah bagus. Amati lagi ciri sisi, rusuk, dan titik sudut pada bangun yang belum tepat.',
      incomplete: 'Coba kembali ke objek dalam komik. Perhatikan bentuknya sebelum memilih jawaban.',
    },
  },
  application: {
    title: 'Bangun Ruang di Sekitarmu',
    intro: 'Setelah mengamati Masjid Al-Akbar, carilah benda di sekitar yang memiliki bentuk bangun ruang serupa.',
    prompt: 'Pilih bangun ruang yang paling sesuai dan jelaskan ciri yang membuatmu yakin.',
    context: 'Benda di rumah dan sekolah dapat membantu kita mengingat bentuk kubus, balok, tabung, kerucut, dan setengah bola.',
    images: [],
    options: [
      { value: 'Kubus', label: 'Kubus' }, { value: 'Balok', label: 'Balok' }, { value: 'Tabung', label: 'Tabung' },
      { value: 'Kerucut', label: 'Kerucut' }, { value: 'Setengah bola', label: 'Setengah bola' },
    ],
  },
  argumentation: {
    questions: [
      { id: 'komik6-arg-1', title: 'Menara Masjid', templePart: 'menara', question: 'Mengapa menara Masjid Al-Akbar dapat diamati sebagai tabung?', photoSrc: '', image: '', photoAlt: 'Menara Masjid Al-Akbar.', shape: 'Tabung', shapeName: 'Tabung', shapeKey: 'tabung', shapeSrc: '', icon: '', aiContext: 'Minta siswa menyebut sisi atas dan alas berbentuk lingkaran, sisi selimut, serta dua rusuk.', feedback: 'Alasanmu dapat diperkuat dengan ciri tabung: 3 sisi dan 2 rusuk.', highlightColor: 'border-cyan-500' },
      { id: 'komik6-arg-2', title: 'Bagian Atas Kubah', templePart: 'bagian atas kubah', question: 'Mengapa bagian atas kubah dapat diamati sebagai kerucut?', photoSrc: '', image: '', photoAlt: 'Bagian atas kubah Masjid Al-Akbar.', shape: 'Kerucut', shapeName: 'Kerucut', shapeKey: 'kerucut', shapeSrc: '', icon: '', aiContext: 'Ajak siswa mencari titik puncak, dua sisi, dan satu rusuk pada bagian atas kubah.', feedback: 'Alasanmu tepat jika menyebut titik puncak dan ciri kerucut lainnya.', highlightColor: 'border-amber-500' },
      { id: 'komik6-arg-3', title: 'Bagian Bawah Kubah', templePart: 'bagian bawah kubah', question: 'Mengapa bagian bawah kubah dapat diamati sebagai setengah bola?', photoSrc: '', image: '', photoAlt: 'Bagian bawah kubah Masjid Al-Akbar.', shape: 'Setengah bola', shapeName: 'Setengah bola', shapeKey: 'setengah-bola', shapeSrc: '', icon: '', aiContext: 'Ajak siswa memperhatikan bentuk yang melengkung seperti sebagian bola dan tidak memiliki titik sudut.', feedback: 'Jelaskan bahwa bentuk lengkung dan tidak adanya titik sudut mendukung pilihan setengah bola.', highlightColor: 'border-sky-500' },
      { id: 'komik6-arg-4', title: 'Ruang Utama', templePart: 'ruang utama', question: 'Mengapa ruang utama masjid dapat diamati sebagai balok?', photoSrc: '', image: '', photoAlt: 'Ruang utama Masjid Al-Akbar.', shape: 'Balok', shapeName: 'Balok', shapeKey: 'balok', shapeSrc: '', icon: '', aiContext: 'Minta siswa menghitung enam sisi berbentuk persegi panjang, dua belas rusuk, dan delapan titik sudut.', feedback: 'Sebutkan ciri balok yang kamu lihat: 6 sisi, 12 rusuk, dan 8 titik sudut.', highlightColor: 'border-emerald-500' },
      { id: 'komik6-arg-5', title: 'Tempat Duduk Wudu', templePart: 'tempat duduk wudu', question: 'Mengapa tempat duduk wudu dapat diamati sebagai kubus?', photoSrc: '', image: '', photoAlt: 'Tempat duduk wudu di ruang wudu.', shape: 'Kubus', shapeName: 'Kubus', shapeKey: 'kubus', shapeSrc: '', icon: '', aiContext: 'Ajak siswa mengamati enam sisi persegi, dua belas rusuk sama panjang, dan delapan titik sudut.', feedback: 'Benar jika alasanmu menghubungkan benda itu dengan enam sisi persegi dan rusuk yang sama panjang.', highlightColor: 'border-violet-500' },
    ],
  },
  resolution: {
    missions: [
      { id: 1, title: 'Misi Menara', part: 'menara', shape: 'Tabung', prompt: 'Pilih ciri yang sesuai dengan menara yang diamati.', options: [{ key: 'a', label: 'Memiliki sisi atas dan alas berbentuk lingkaran' }, { key: 'b', label: 'Memiliki semua sisi berbentuk persegi' }], correctKey: 'a', answer: 'Tabung memiliki sisi atas dan alas berbentuk lingkaran.', formula: '3 sisi dan 2 rusuk', explanation: 'Ciri itu sesuai dengan tabung yang dijelaskan pada halaman pengamatan menara.', aiHint: 'Cari ciri menara yang berkaitan dengan lingkaran.', context: 'Menara Masjid Al-Akbar', accent: 'cyan', illustration: '' },
      { id: 2, title: 'Misi Kubah Atas', part: 'bagian atas kubah', shape: 'Kerucut', prompt: 'Ciri apa yang membantu mengenali bagian atas kubah sebagai kerucut?', options: [{ key: 'a', label: 'Memiliki titik puncak' }, { key: 'b', label: 'Memiliki delapan titik sudut' }], correctKey: 'a', answer: 'Kerucut memiliki titik puncak.', formula: '2 sisi dan 1 rusuk', explanation: 'Bagian atas kubah memiliki bentuk yang mengarah ke satu titik puncak.', aiHint: 'Perhatikan bagian kubah yang meruncing ke atas.', context: 'Kubah utama Masjid Al-Akbar', accent: 'amber', illustration: '' },
      { id: 3, title: 'Misi Ruang Utama', part: 'ruang utama', shape: 'Balok', prompt: 'Berapa sisi yang dimiliki balok menurut penjelasan dalam komik?', options: [{ key: 'a', label: '6 sisi' }, { key: 'b', label: '3 sisi' }], correctKey: 'a', answer: 'Balok memiliki 6 sisi.', formula: '6 sisi, 12 rusuk, dan 8 titik sudut', explanation: 'Ruang utama diamati sebagai balok dengan sisi berbentuk persegi panjang.', aiHint: 'Ingat tiga angka ciri balok yang disebut Bu Syarla.', context: 'Ruang utama masjid', accent: 'emerald', illustration: '' },
      { id: 4, title: 'Misi Tempat Duduk Wudu', part: 'tempat duduk wudu', shape: 'Kubus', prompt: 'Ciri mana yang paling sesuai dengan kubus?', options: [{ key: 'a', label: '6 sisi berbentuk persegi dan 12 rusuk sama panjang' }, { key: 'b', label: 'Memiliki sisi selimut dan titik puncak' }], correctKey: 'a', answer: 'Kubus memiliki 6 sisi persegi dan 12 rusuk sama panjang.', formula: '6 sisi, 12 rusuk, dan 8 titik sudut', explanation: 'Tempat duduk wudu diamati sebagai kubus.', aiHint: 'Bandingkan sisi persegi kubus dengan sisi selimut tabung.', context: 'Ruang wudu masjid', accent: 'violet', illustration: '' },
      { id: 5, title: 'Misi Kubah Bawah', part: 'bagian bawah kubah', shape: 'Setengah bola', prompt: 'Mengapa bagian bawah kubah bukan kerucut?', options: [{ key: 'a', label: 'Karena bentuknya melengkung seperti sebagian bola' }, { key: 'b', label: 'Karena memiliki titik puncak' }], correctKey: 'a', answer: 'Bagian bawah kubah melengkung seperti setengah bola dan tidak memiliki titik sudut.', formula: 'Sisi lengkung dan bagian tertutup', explanation: 'Perhatikan perbedaan bentuk melengkung dengan bagian atas kubah yang meruncing.', aiHint: 'Cari bentuk yang tidak memiliki titik puncak.', context: 'Bagian bawah kubah masjid', accent: 'sky', illustration: '' },
    ],
  },
  introspection: {
    checklist: ['Aku dapat menyebutkan kubus, balok, tabung, kerucut, dan setengah bola.', 'Aku dapat menyebutkan sisi, rusuk, titik sudut, atau titik puncak pada bangun ruang.', 'Aku dapat menghubungkan bangun ruang dengan bagian Masjid Al-Akbar.', 'Aku dapat menjelaskan alasan saat memilih sebuah bangun ruang.'],
    completionMessage: 'Hebat! Kamu sudah belajar mengenali bangun ruang dari arsitektur Masjid Al-Akbar Surabaya.',
    nextPrompt: 'Amati satu benda di sekitarmu. Bangun ruang apa yang paling mirip dan apa cirinya?',
  },
  report: {
    summary: 'Pada Komik 6, siswa belajar bangun ruang melalui pengamatan arsitektur Masjid Al-Akbar Surabaya. Siswa mengenali tabung pada menara, kerucut dan setengah bola pada kubah, balok pada ruang utama, serta kubus pada tempat duduk wudu.',
    learnedShapes: ['Tabung', 'Kerucut', 'Setengah bola', 'Balok', 'Kubus'],
  },
};
