import kubusIllustration from '../assets/resolution/kubus.svg';
import balokIllustration from '../assets/resolution/balok.svg';
import prismaIllustration from '../assets/resolution/prismasegiempat.svg';
import limasIllustration from '../assets/resolution/limassegiempat.svg';
import kerucutIllustration from '../assets/resolution/kerucut.svg';

export const resolutionContent = {
  missions: [
    {
      id: 1,
      title: 'Misi 1 · Volume Kubus',
      part: 'Kubus',
      shape: 'Kubus',
      prompt: 'Sebuah kubus memiliki panjang rusuk 8 cm. Hitung volumenya.',
      problemData: ['Rusuk (s) = 8 cm'],
      options: [
        { key: 'A', label: '256 cm³' },
        { key: 'B', label: '384 cm³' },
        { key: 'C', label: '512 cm³' },
        { key: 'D', label: '640 cm³' },
      ],
      correctKey: 'C',
      answer: '512 cm³',
      formula: 'V = s × s × s',
      explanation: '8 × 8 × 8 = 512',
      hint: 'Kalikan rusuk sebanyak tiga kali.',
      correctFeedback: 'Tepat! Volume kubus diperoleh dari perkalian rusuk tiga kali.',
      incorrectFeedback: 'Belum tepat. Kubus memiliki rusuk yang sama pada semua sisi, jadi volumenya adalah s × s × s.',
      aiHint: 'Gunakan rumus volume kubus: V = s³.',
      context: 'Bangun ruang kubus pada Candi Jawi membantu siswa menghubungkan bentuk tiga dimensi dengan konsep volume yang rapi.',
      accent: 'from-primary-600 to-primary-700',
      illustration: kubusIllustration.src,
    },
    {
      id: 2,
      title: 'Misi 2 · Volume Balok',
      part: 'Balok',
      shape: 'Balok',
      prompt: 'Sebuah balok memiliki p = 12 cm, l = 6 cm, dan t = 5 cm. Hitung volumenya.',
      problemData: ['Panjang (p) = 12 cm', 'Lebar (l) = 6 cm', 'Tinggi (t) = 5 cm'],
      options: [
        { key: 'A', label: '300 cm³' },
        { key: 'B', label: '320 cm³' },
        { key: 'C', label: '360 cm³' },
        { key: 'D', label: '400 cm³' },
      ],
      correctKey: 'C',
      answer: '360 cm³',
      formula: 'V = p × l × t',
      explanation: '12 × 6 × 5 = 360',
      hint: 'Kalikan panjang, lebar, dan tinggi dengan hati-hati.',
      correctFeedback: 'Tepat! Volume balok diperoleh dari perkalian panjang, lebar, dan tinggi.',
      incorrectFeedback: 'Belum tepat. Periksa kembali perkalian panjang, lebar, dan tinggi pada balok.',
      aiHint: 'Kalikan panjang, lebar, dan tinggi dengan cermat.',
      context: 'Bangun ruang balok pada Candi Jawi membantu siswa melihat bentuk yang panjang, lebar, dan tinggi berbeda.',
      accent: 'from-secondary-500 to-secondary-600',
      illustration: balokIllustration.src,
    },
    {
      id: 3,
      title: 'Misi 3 · Volume Prisma Segi Empat',
      part: 'Prisma Segi Empat',
      shape: 'Prisma Segi Empat',
      prompt: 'Sebuah prisma segi empat memiliki luas alas 36 cm² dan tinggi 10 cm. Volume prisma tersebut adalah?',
      problemData: ['Luas alas = 36 cm²', 'Tinggi prisma = 10 cm'],
      options: [
        { key: 'A', label: '300 cm³' },
        { key: 'B', label: '360 cm³' },
        { key: 'C', label: '420 cm³' },
        { key: 'D', label: '480 cm³' },
      ],
      correctKey: 'B',
      answer: '360 cm³',
      formula: 'V = Luas Alas × Tinggi',
      explanation: '36 × 10 = 360',
      hint: 'Kalikan luas alas dengan tinggi prisma.',
      correctFeedback: 'Benar! Volume prisma segi empat adalah luas alas dikalikan tinggi.',
      incorrectFeedback: 'Belum tepat. Ingat, volume prisma adalah luas alas dikali tinggi.',
      aiHint: 'Gunakan rumus volume prisma: V = Luas Alas × Tinggi.',
      context: 'Prisma segi empat pada Candi Jawi membantu siswa memahami hubungan antara alas dan tinggi pada bangun ruang.',
      accent: 'from-amber-500 to-orange-500',
      illustration: prismaIllustration.src,
    },
    {
      id: 4,
      title: 'Misi 4 · Volume Limas Segi Empat',
      part: 'Limas Segi Empat',
      shape: 'Limas Segi Empat',
      prompt: 'Sebuah limas segi empat memiliki luas alas 64 cm² dan tinggi 9 cm. Volume limas tersebut adalah?',
      problemData: ['Luas alas = 64 cm²', 'Tinggi limas = 9 cm'],
      options: [
        { key: 'A', label: '144 cm³' },
        { key: 'B', label: '192 cm³' },
        { key: 'C', label: '240 cm³' },
        { key: 'D', label: '288 cm³' },
      ],
      correctKey: 'B',
      answer: '192 cm³',
      formula: 'V = 1/3 × Luas Alas × Tinggi',
      explanation: '1/3 × 64 × 9 = 192',
      hint: 'Jangan lupa bagi hasilnya dengan 3.',
      correctFeedback: 'Tepat! Limas segi empat memiliki volume sepertiga dari prisma yang alas dan tingginya sama.',
      incorrectFeedback: 'Belum tepat. Ingat, volume limas adalah sepertiga dari hasil perkalian luas alas dan tinggi.',
      aiHint: 'Gunakan rumus volume limas: V = 1/3 × Luas Alas × Tinggi.',
      context: 'Limas segi empat pada Candi Jawi membantu siswa memahami bentuk yang meruncing ke satu puncak.',
      accent: 'from-emerald-500 to-emerald-600',
      illustration: limasIllustration.src,
    },
    {
      id: 5,
      title: 'Misi 5 · Volume Kerucut',
      part: 'Kerucut',
      shape: 'Kerucut',
      prompt: 'Sebuah kerucut memiliki r = 7 cm dan t = 12 cm. Gunakan π = 22/7. Volume kerucut tersebut adalah?',
      problemData: ['Jari-jari (r) = 7 cm', 'Tinggi (t) = 12 cm', 'π = 22/7'],
      options: [
        { key: 'A', label: '528 cm³' },
        { key: 'B', label: '616 cm³' },
        { key: 'C', label: '672 cm³' },
        { key: 'D', label: '728 cm³' },
      ],
      correctKey: 'B',
      answer: '616 cm³',
      formula: 'V = 1/3 × π × r² × t',
      explanation: '1/3 × 22/7 × 49 × 12 = 616',
      hint: 'Hitung r² terlebih dahulu, lalu bagi hasilnya dengan 3.',
      correctFeedback: 'Sangat tepat! Kerucut memiliki volume sepertiga dari tabung dengan jari-jari dan tinggi yang sama.',
      incorrectFeedback: 'Belum tepat. Hitung r² dulu, lalu kalikan dengan tinggi dan π, lalu bagi tiga.',
      aiHint: 'Mulai dari menghitung r² = 49, lalu kalikan dengan tinggi dan π, lalu bagi 3.',
      context: 'Kerucut pada Candi Jawi membantu siswa melihat hubungan antara alas bundar dan puncak yang meruncing.',
      accent: 'from-fuchsia-500 to-purple-600',
      illustration: kerucutIllustration.src,
    },
  ],
};
