import cubeIllustration from '../assets/resolution/cube.svg';
import cuboidIllustration from '../assets/resolution/cuboid.svg';
import prismIllustration from '../assets/resolution/prism.svg';
import pyramidIllustration from '../assets/resolution/pyramid.svg';
import coneIllustration from '../assets/resolution/cone.svg';

export const resolutionContent = {
  missions: [
    {
      id: 1,
      title: 'Misi 1 · Volume Kubus',
      part: 'Kubus',
      shape: 'Kubus',
      prompt: 'Sebuah kubus mempunyai panjang rusuk 8 cm. Berapa volumenya?',
      problemData: ['Rusuk (s) = 8 cm'],
      options: [
        { key: 'A', label: '256 cm³' },
        { key: 'B', label: '384 cm³' },
        { key: 'C', label: '512 cm³' },
        { key: 'D', label: '640 cm³' },
      ],
      correctKey: 'C',
      answer: '512 cm³',
      formula: 'V = s³',
      explanation: '8 × 8 × 8 = 512',
      hint: 'Kalikan rusuk sebanyak tiga kali.',
      correctFeedback: 'Tepat! Volume kubus dihitung dengan mengalikan rusuk tiga kali.',
      incorrectFeedback: 'Belum tepat. Ingat, kubus memiliki rusuk yang sama, sehingga volumenya adalah s × s × s.',
      aiHint: 'Gunakan rumus volume kubus: V = s³.',
      context: 'Bangun ruang kubus dipakai untuk menerapkan konsep volume pada objek beraturan.',
      accent: 'from-primary-600 to-primary-700',
      illustration: cubeIllustration.src,
    },
    {
      id: 2,
      title: 'Misi 2 · Volume Balok',
      part: 'Balok',
      shape: 'Balok',
      prompt: 'Panjang balok 12 cm, lebar 5 cm, tinggi 4 cm. Berapa volumenya?',
      problemData: ['Panjang (p) = 12 cm', 'Lebar (l) = 5 cm', 'Tinggi (t) = 4 cm'],
      options: [
        { key: 'A', label: '180 cm³' },
        { key: 'B', label: '220 cm³' },
        { key: 'C', label: '240 cm³' },
        { key: 'D', label: '260 cm³' },
      ],
      correctKey: 'C',
      answer: '240 cm³',
      formula: 'V = p × l × t',
      explanation: '12 × 5 × 4 = 240',
      hint: 'Kalikan panjang, lebar, dan tinggi.',
      correctFeedback: 'Tepat! Volume balok diperoleh dari perkalian panjang, lebar, dan tinggi.',
      incorrectFeedback: 'Belum tepat. Periksa kembali perkalian panjang, lebar, dan tinggi.',
      aiHint: 'Kalikan panjang, lebar, dan tinggi dengan hati-hati.',
      context: 'Bangun ruang balok dipakai untuk menerapkan konsep volume pada benda yang memiliki tiga ukuran berbeda.',
      accent: 'from-secondary-500 to-secondary-600',
      illustration: cuboidIllustration.src,
    },
    {
      id: 3,
      title: 'Misi 3 · Volume Prisma Segi Empat',
      part: 'Prisma Segi Empat',
      shape: 'Prisma Segi Empat',
      prompt: 'Sebuah prisma memiliki luas alas 30 cm² dan tinggi 10 cm. Berapa volumenya?',
      problemData: ['Luas alas = 30 cm²', 'Tinggi = 10 cm'],
      options: [
        { key: 'A', label: '200 cm³' },
        { key: 'B', label: '250 cm³' },
        { key: 'C', label: '300 cm³' },
        { key: 'D', label: '350 cm³' },
      ],
      correctKey: 'C',
      answer: '300 cm³',
      formula: 'V = Luas Alas × Tinggi',
      explanation: '30 × 10 = 300',
      hint: 'Cari luas alas terlebih dahulu.',
      correctFeedback: 'Benar! Volume prisma segi empat didapatkan dari luas alas dikalikan tinggi.',
      incorrectFeedback: 'Belum tepat. Ingat bahwa volume prisma adalah luas alas dikali tinggi.',
      aiHint: 'Gunakan rumus volume prisma: V = Luas Alas × Tinggi.',
      context: 'Prisma segi empat membantu siswa memahami hubungan antara alas dan tinggi pada bangun ruang.',
      accent: 'from-amber-500 to-orange-500',
      illustration: prismIllustration.src,
    },
    {
      id: 4,
      title: 'Misi 4 · Volume Limas Segi Empat',
      part: 'Limas Segi Empat',
      shape: 'Limas Segi Empat',
      prompt: 'Luas alas limas 81 cm² dan tinggi 12 cm. Berapa volumenya?',
      problemData: ['Luas alas = 81 cm²', 'Tinggi = 12 cm'],
      options: [
        { key: 'A', label: '243 cm³' },
        { key: 'B', label: '324 cm³' },
        { key: 'C', label: '486 cm³' },
        { key: 'D', label: '648 cm³' },
      ],
      correctKey: 'B',
      answer: '324 cm³',
      formula: 'V = 1/3 × Luas Alas × Tinggi',
      explanation: '1/3 × 81 × 12 = 324',
      hint: 'Jangan lupa dikali 1/3.',
      correctFeedback: 'Tepat! Limas segi empat memiliki volume sepertiga dari prisma dengan alas dan tinggi yang sama.',
      incorrectFeedback: 'Belum tepat. Ingat, volume limas adalah sepertiga dari hasil perkalian luas alas dan tinggi.',
      aiHint: 'Gunakan rumus volume limas: V = 1/3 × Luas Alas × Tinggi.',
      context: 'Limas segi empat membantu siswa memahami bagian puncak yang meruncing pada bangun ruang.',
      accent: 'from-emerald-500 to-emerald-600',
      illustration: pyramidIllustration.src,
    },
    {
      id: 5,
      title: 'Misi 5 · Volume Kerucut',
      part: 'Kerucut',
      shape: 'Kerucut',
      prompt: 'Jari-jari kerucut 7 cm, tinggi 12 cm. Gunakan π = 22/7. Berapa volumenya?',
      problemData: ['Jari-jari (r) = 7 cm', 'Tinggi (t) = 12 cm', 'π = 22/7'],
      options: [
        { key: 'A', label: '504 cm³' },
        { key: 'B', label: '616 cm³' },
        { key: 'C', label: '672 cm³' },
        { key: 'D', label: '728 cm³' },
      ],
      correctKey: 'B',
      answer: '616 cm³',
      formula: 'V = 1/3 × π × r² × t',
      explanation: '1/3 × 22/7 × 49 × 12 = 616',
      hint: 'Hitung r² terlebih dahulu.',
      correctFeedback: 'Sangat tepat! Kerucut memiliki volume sepertiga dari tabung dengan jari-jari dan tinggi yang sama.',
      incorrectFeedback: 'Belum tepat. Hitung r² dulu, lalu kalikan dengan tinggi dan π, lalu bagi tiga.',
      aiHint: 'Mulai dari menghitung r² = 49, lalu kalikan dengan tinggi dan π, lalu bagi 3.',
      context: 'Kerucut membantu siswa menerapkan rumus volume pada bangun ruang yang meruncing.',
      accent: 'from-fuchsia-500 to-purple-600',
      illustration: coneIllustration.src,
    },
  ],
};
