import type { ComicContentPackageLike } from '../../types';
import persegiIllustration from '@/features/comics/comic-3/assets/identification/persegi.svg';
import persegiPlaceholder from '@/features/comics/comic-3/assets/placeholders/persegi.svg';
import persegiHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/persegi-highlight.svg';
import persegiPanjangPlaceholder from '@/features/comics/comic-3/assets/placeholders/persegi-panjang.svg';
import persegiPanjangHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/persegi-panjang-highlight.svg';
import segitigaPlaceholder from '@/features/comics/comic-3/assets/placeholders/segitiga.svg';
import segitigaHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/segitiga-highlight.svg';
import trapesiumPlaceholder from '@/features/comics/comic-3/assets/placeholders/trapesium.svg';
import trapesiumHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/trapesium-highlight.svg';
import lingkaranPlaceholder from '@/features/comics/comic-3/assets/placeholders/lingkaran.svg';
import lingkaranHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/lingkaran-highlight.svg';
import jajarGenjangPlaceholder from '@/features/comics/comic-3/assets/placeholders/jajar-genjang.svg';
import jajarGenjangHighlightPlaceholder from '@/features/comics/comic-3/assets/placeholders/jajar-genjang-highlight.svg';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 3,
    title: 'Petualangan di Rumah Gajah Mungkur',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Rumah Gajah Mungkur, Gresik',
    classLevel: 'II',
    cover: '/comics/komik-3/cover.png',
    thumbnail: '/comics/komik-3/thumbnail.png',
    learningTargets: [
      'Mengamati bangun datar yang muncul pada Rumah Gajah Mungkur.',
      'Menghubungkan bentuk persegi, persegi panjang, segitiga, trapesium, belah ketupat, dan lingkaran dengan objek nyata.',
      'Menggunakan bahasa sederhana untuk menjelaskan ciri setiap bangun datar.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Rumah Gajah Mungkur.',
  },
  learningObjects: [
    {
      id: 'komik3-persegi',
      title: 'Persegi',
      description: 'Bentuk persegi pada bagian halaman bangunan.',
      page: 1,
      qrImage: '/images/navigation/default.svg',
      navImage: persegiPlaceholder.src,
      objectImage: persegiPlaceholder.src,
      image: persegiPlaceholder.src,
      highlightImage: persegiHighlightPlaceholder.src,
      observationQuestion: 'Apa yang kamu perhatikan ketika bangun persegi ini berganti menjadi highlight?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri persegi yang terlihat pada bangunan ini.',
      question: 'Apa ciri persegi?',
      answer: 'Persegi memiliki empat sisi sama panjang dan empat sudut siku-siku.',
      feedback: 'Benar, persegi aman dikenali karena semua sisinya sama.',
      characteristics: ['Empat sisi sama panjang', 'Empat sudut siku-siku', 'Semua sisi sejajar', 'Bentuknya seperti kotak'],
    },
    {
      id: 'komik3-persegi-panjang',
      title: 'Persegi Panjang',
      description: 'Bentuk persegi panjang pada dinding dan lantai.',
      page: 2,
      qrImage: '/images/navigation/default.svg',
      navImage: persegiPanjangPlaceholder.src,
      objectImage: persegiPanjangPlaceholder.src,
      image: persegiPanjangPlaceholder.src,
      highlightImage: persegiPanjangHighlightPlaceholder.src,
      observationQuestion: 'Bagian mana pada gambar ini yang menonjol sebagai persegi panjang?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri persegi panjang yang terlihat pada bangunan ini.',
      question: 'Apa ciri persegi panjang?',
      answer: 'Persegi panjang memiliki dua pasang sisi sama panjang dan empat sudut siku-siku.',
      feedback: 'Benar, persegi panjang mudah dikenali dari sisi panjang dan pendeknya.',
      characteristics: ['Dua pasang sisi sama panjang', 'Empat sudut siku-siku', 'Panjang dan lebar berbeda', 'Sisi yang sejajar berhadapan'],
    },
    {
      id: 'komik3-segitiga',
      title: 'Segitiga',
      description: 'Bentuk atap rumah yang tajam.',
      page: 3,
      qrImage: '/images/navigation/default.svg',
      navImage: segitigaPlaceholder.src,
      objectImage: segitigaPlaceholder.src,
      image: segitigaPlaceholder.src,
      highlightImage: segitigaHighlightPlaceholder.src,
      observationQuestion: 'Bagaimana highlight membantu kamu melihat sisi dan sudut segitiga ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan mengapa atap dapat dipahami sebagai segitiga.',
      question: 'Mengapa atap bisa dikatakan segitiga?',
      answer: 'Karena atap memiliki tiga sisi dan tiga sudut.',
      feedback: 'Benar, segitiga memiliki tiga sisi dan tiga sudut.',
      characteristics: ['Tiga sisi dan tiga sudut', 'Biasanya terlihat tajam', 'Memiliki dua sisi yang bisa sejajar', 'Bentuknya seperti gunung kecil'],
    },
    {
      id: 'komik3-trapesium',
      title: 'Trapesium',
      description: 'Bentuk trapesium pada ornamen bangunan.',
      page: 4,
      qrImage: '/images/navigation/default.svg',
      navImage: trapesiumPlaceholder.src,
      objectImage: trapesiumPlaceholder.src,
      image: trapesiumPlaceholder.src,
      highlightImage: trapesiumHighlightPlaceholder.src,
      observationQuestion: 'Apa yang berubah ketika highlight ditampilkan pada bentuk trapesium ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri trapesium yang terdapat pada ornamen bangunan ini.',
      question: 'Apa ciri trapesium?',
      answer: 'Trapesium memiliki sepasang sisi sejajar dan dua sisi yang tidak sejajar.',
      feedback: 'Bagus, kamu bisa mengenali trapesium dari sisi sejajarnya.',
      characteristics: ['Satu pasang sisi sejajar', 'Dua sisi tidak sejajar', 'Empat sudut', 'Bentuknya seperti atap miring'],
    },
    {
      id: 'komik3-lingkaran',
      title: 'Lingkaran',
      description: 'Bentuk lingkaran pada hiasan bundar.',
      page: 5,
      qrImage: '/images/navigation/default.svg',
      navImage: lingkaranPlaceholder.src,
      objectImage: lingkaranPlaceholder.src,
      image: lingkaranPlaceholder.src,
      highlightImage: lingkaranHighlightPlaceholder.src,
      observationQuestion: 'Bagaimana highlight memudahkan kamu melihat lingkaran ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri lingkaran yang terlihat pada hiasan bundar ini.',
      question: 'Apa ciri lingkaran?',
      answer: 'Lingkaran memiliki semua titik pada tepi yang sama jaraknya dari pusat.',
      feedback: 'Benar, lingkaran terlihat seperti bentuk bulat sempurna.',
      characteristics: ['Satu garis lengkung tertutup', 'Tidak memiliki sudut', 'Semua titik sama jauh dari pusat', 'Bentuknya seperti roda'],
    },
    {
      id: 'komik3-jajar-genjang',
      title: 'Jajar Genjang',
      description: 'Bentuk jajar genjang pada pola lantai.',
      page: 6,
      qrImage: '/images/navigation/default.svg',
      navImage: jajarGenjangPlaceholder.src,
      objectImage: jajarGenjangPlaceholder.src,
      image: jajarGenjangPlaceholder.src,
      highlightImage: jajarGenjangHighlightPlaceholder.src,
      observationQuestion: 'Perhatikan pola garis pada jajar genjang ini; apa yang membuatnya berbeda dari trapezium?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: 'Jelaskan ciri jajar genjang yang kamu lihat pada pola lantai.',
      question: 'Apa ciri jajar genjang?',
      answer: 'Jajar genjang memiliki dua pasang sisi sejajar yang sama panjang.',
      feedback: 'Bagus, kamu bisa mengenali jajar genjang dari sisi-sisinya yang sejajar.',
      characteristics: ['Dua pasang sisi sejajar', 'Sisi-sisi sama panjang', 'Empat sudut', 'Bentuknya miring ke samping'],
    },
  ],
  qrCode: [
    { id: 'komik3-qr-1', imageSrc: '/images/navigation/default.svg', alt: 'QR Persegi', label: 'Persegi', description: 'Scan untuk melihat bentuk persegi.' },
    { id: 'komik3-qr-2', imageSrc: '/images/navigation/default.svg', alt: 'QR Segitiga', label: 'Segitiga', description: 'Scan untuk melihat bentuk segitiga.' },
  ],
  model3D: [
    { id: 'komik3-model-1', title: 'Persegi', arUrl: '', page: 1, description: 'Model 3D persegi untuk pengamatan sederhana.' },
    { id: 'komik3-model-2', title: 'Segitiga', arUrl: '', page: 2, description: 'Model 3D segitiga untuk pengamatan sudut.' },
  ],
  aiPrompt: {
    navigation: 'Bantu siswa mengenali bangun datar sederhana dengan bahasa yang mudah dipahami.',
    objectTutor: 'Jelaskan bangun datar dengan contoh yang dekat dengan kehidupan siswa.',
    application: 'Bantu siswa menghubungkan bangun datar dengan benda nyata di sekitar.',
    argumentation: 'Beri umpan balik sederhana tentang alasan siswa.',
    resolution: 'Bimbing siswa menyelesaikan latihan bangun datar sederhana.',
    introspection: 'Buat refleksi singkat dengan bahasa yang sederhana dan positif.',
  },
  identification: {
    questions: [
      {
        id: 'komik3-ident-1',
        question: 'Apa saja bentuk bangun datar yang kamu temukan pada Rumah Gajah Mungkur?',
        image: persegiIllustration.src,
        imageAlt: 'Ilustrasi berbagai bangun datar yang terlihat pada Rumah Gajah Mungkur.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: true },
          { text: 'Trapesium', correct: true },
          { text: 'Belah Ketupat', correct: true },
          { text: 'Lingkaran', correct: true },
        ],
        explanation: 'Pada Rumah Gajah Mungkur, kamu bisa menemukan beberapa bangun datar seperti persegi, persegi panjang, segitiga, trapesium, belah ketupat, dan lingkaran.',
      },
    ],
    feedback: {
      complete: 'Sangat bagus! Kamu berhasil mengenali bangun datar yang ada pada Rumah Gajah Mungkur.',
      partial: 'Masih ada beberapa bentuk yang perlu diperiksa lagi.',
      incomplete: 'Coba lihat kembali bagian rumah yang kamu amati dan cari bentuk yang paling cocok.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Temukan bangun datar yang ada di sekitar benda',
    prompt: 'Pilih bangun datar yang paling cocok dengan benda yang kamu amati.',
    context: 'Benda-benda yang ada di sekitar rumah dan bangunan bersejarah.',
    images: [
      { src: '/images/navigation/default.svg', alt: 'Bentuk persegi', label: 'Persegi', description: 'Perhatikan sisi dan sudutnya.' },
      { src: '/images/navigation/default.svg', alt: 'Bentuk segitiga', label: 'Segitiga', description: 'Perhatikan sisi dan sudutnya.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Lingkaran', label: 'Lingkaran' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik3-arg-1',
        templePart: 'bagian depan rumah',
        question: 'Mengapa bentuk bagian depan rumah bisa dipahami sebagai persegi?',
        photoSrc: '/images/navigation/default.svg',
        photoAlt: 'Bagian depan rumah',
        shapeName: 'Persegi',
        shapeKey: 'persegi',
        shapeSrc: '/images/navigation/default.svg',
        highlightColor: 'border-primary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Bagian Depan',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 4 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '8 cm²' },
          { key: 'B', label: '12 cm²' },
          { key: 'C', label: '16 cm²' },
          { key: 'D', label: '20 cm²' },
        ],
        correctKey: 'C',
        answer: '16 cm²',
        formula: 'L = s × s = 4 × 4 = 16 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi.',
        context: 'Bentuk yang kamu lihat pada bangunan rumah.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/default.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya dapat mengenali bentuk bangun datar sederhana.',
      'Saya tahu perbedaan persegi dan segitiga.',
      'Saya lebih percaya diri mengamati benda di sekitar.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada komik ini.',
    nextPrompt: 'Kamu bisa mengulang lagi bila ingin lebih percaya diri.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar sederhana.',
    learnedShapes: ['Persegi', 'Segitiga'],
  },
};
