import type { ComicContentPackageLike } from '../../types';
import persegiIllustration from '@/features/comics/comic-3/assets/identification/persegi.svg';
import persegiNav from '@/features/comics/comic-3/assets/navigation/persegi.svg';
import persegiHighlightNav from '@/features/comics/comic-3/assets/navigation/persegi-highlight.svg';
import persegiPanjangNav from '@/features/comics/comic-3/assets/navigation/persegi-panjang.svg';
import persegiPanjangHighlightNav from '@/features/comics/comic-3/assets/navigation/persegi-panjang-highlight.svg';
import segitigaNav from '@/features/comics/comic-3/assets/navigation/segitiga.svg';
import segitigaHighlightNav from '@/features/comics/comic-3/assets/navigation/segitiga-highlight.svg';
import trapesiumNav from '@/features/comics/comic-3/assets/navigation/trapesium.svg';
import trapesiumHighlightNav from '@/features/comics/comic-3/assets/navigation/trapesium-highlight.svg';
import lingkaranNav from '@/features/comics/comic-3/assets/navigation/lingkaran.svg';
import lingkaranHighlightNav from '@/features/comics/comic-3/assets/navigation/lingkaran-highlight.svg';
import belahKetupatNav from '@/features/comics/comic-3/assets/navigation/belah-ketupat.svg';
import belahKetupatHighlightNav from '@/features/comics/comic-3/assets/navigation/belah-ketupat-highlight.svg';
import { 
  AlapImg, 
  AtapKanopiImg, 
  JendelaImg, 
  OrnamentPagarBelahKetupatImg, 
  OrnamentPagarLingkaranImg, 
  PintuImg 
} from '@/features/comics/comic-3/assets/argumentation';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 3,
    title: 'Petualangan di Rumah Gajah Mungkur',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Rumah Gajah Mungkur, Gresik',
    classLevel: 'II',
    cover: '/comics/komik-3/cover.png',
    thumbnail: '/comics/komik-3/thumbnail.png',
    learningTargets: [
      'Mengamati bangun datar yang muncul pada Rumah Gajah Mungkur.',
      'Menghubungkan bentuk persegi, persegi panjang, segitiga, trapesium, belah ketupat, dan lingkaran dengan objek nyata.',
      'Menggunakan bahasa sederhana untuk menjelaskan ciri setiap bangun datar.',
    ],
    synopsis: 'Pembelajaran untuk bangun datar di Rumah Gajah Mungkur.',
  },
  learningObjects: [
    {
      id: 'komik3-persegi',
      title: 'Persegi',
      description: 'Bentuk persegi pada bagian halaman bangunan.',
      page: 1,
      qrImage: '/images/navigation/default.svg',
      navImage: persegiNav.src,
      objectImage: persegiNav.src,
      image: persegiNav.src,
      highlightImage: persegiHighlightNav.src,
      observationQuestion: 'Apa yang kamu perhatikan ketika bangun persegi ini berganti menjadi highlight?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan ciri persegi yang terlihat pada bangunan ini.`,
      question: 'Apa ciri persegi?',
      answer: 'Persegi memiliki empat sisi sama panjang dan empat sudut siku-siku.',
      feedback: 'Benar, persegi aman dikenali karena semua sisinya sama.',
      characteristics: ['Empat sisi sama panjang', 'Empat sudut siku-siku', 'Semua sisi sejajar', 'Bentuknya seperti kotak'],
    },
    {
      id: 'komik3-persegi-panjang',
      title: 'Persegi Panjang',
      description: 'Bentuk persegi panjang pada dinding dan lantai.',
      page: 2,
      qrImage: '/images/navigation/default.svg',
      navImage: persegiPanjangNav.src,
      objectImage: persegiPanjangNav.src,
      image: persegiPanjangNav.src,
      highlightImage: persegiPanjangHighlightNav.src,
      observationQuestion: 'Bagian mana pada gambar ini yang menonjol sebagai persegi panjang?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan ciri persegi panjang yang terlihat pada bangunan ini.`,
      question: 'Apa ciri persegi panjang?',
      answer: 'Persegi panjang memiliki dua pasang sisi sama panjang dan empat sudut siku-siku.',
      feedback: 'Benar, persegi panjang mudah dikenali dari sisi panjang dan pendeknya.',
      characteristics: ['Dua pasang sisi sama panjang', 'Empat sudut siku-siku', 'Panjang dan lebar berbeda', 'Sisi yang sejajar berhadapan'],
    },
    {
      id: 'komik3-segitiga',
      title: 'Segitiga',
      description: 'Bentuk atap rumah yang tajam.',
      page: 3,
      qrImage: '/images/navigation/default.svg',
      navImage: segitigaNav.src,
      objectImage: segitigaNav.src,
      image: segitigaNav.src,
      highlightImage: segitigaHighlightNav.src,
      observationQuestion: 'Bagaimana highlight membantu kamu melihat sisi dan sudut segitiga ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan mengapa atap dapat dipahami sebagai segitiga.`,
      question: 'Mengapa atap bisa dikatakan segitiga?',
      answer: 'Karena atap memiliki tiga sisi dan tiga sudut.',
      feedback: 'Benar, segitiga memiliki tiga sisi dan tiga sudut.',
      characteristics: ['Tiga sisi dan tiga sudut', 'Biasanya terlihat tajam', 'Memiliki dua sisi yang bisa sejajar', 'Bentuknya seperti gunung kecil'],
    },
    {
      id: 'komik3-trapesium',
      title: 'Trapesium',
      description: 'Bentuk trapesium pada ornamen bangunan.',
      page: 4,
      qrImage: '/images/navigation/default.svg',
      navImage: trapesiumNav.src,
      objectImage: trapesiumNav.src,
      image: trapesiumNav.src,
      highlightImage: trapesiumHighlightNav.src,
      observationQuestion: 'Apa yang berubah ketika highlight ditampilkan pada bentuk trapesium ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan ciri trapesium yang terdapat pada ornamen bangunan ini.`,
      question: 'Apa ciri trapesium?',
      answer: 'Trapesium memiliki sepasang sisi sejajar dan dua sisi yang tidak sejajar.',
      feedback: 'Bagus, kamu bisa mengenali trapesium dari sisi sejajarnya.',
      characteristics: ['Satu pasang sisi sejajar', 'Dua sisi tidak sejajar', 'Empat sudut', 'Bentuknya seperti atap miring'],
    },
    {
      id: 'komik3-lingkaran',
      title: 'Lingkaran',
      description: 'Bentuk lingkaran pada hiasan bundar.',
      page: 5,
      qrImage: '/images/navigation/default.svg',
      navImage: lingkaranNav.src,
      objectImage: lingkaranNav.src,
      image: lingkaranNav.src,
      highlightImage: lingkaranHighlightNav.src,
      observationQuestion: 'Bagaimana highlight memudahkan kamu melihat lingkaran ini?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan ciri lingkaran yang terlihat pada hiasan bundar ini.`,
      question: 'Apa ciri lingkaran?',
      answer: 'Lingkaran memiliki semua titik pada tepi yang sama jaraknya dari pusat.',
      feedback: 'Benar, lingkaran terlihat seperti bentuk bulat sempurna.',
      characteristics: ['Satu garis lengkung tertutup', 'Tidak memiliki sudut', 'Semua titik sama jauh dari pusat', 'Bentuknya seperti roda'],
    },
    {
      id: 'komik3-belah-ketupat',
      title: 'Belah Ketupat',
      description: 'Bentuk belah ketupat pada pola lantai.',
      page: 6,
      qrImage: '/images/navigation/default.svg',
      navImage: belahKetupatNav.src,
      objectImage: belahKetupatNav.src,
      image: belahKetupatNav.src,
      highlightImage: belahKetupatHighlightNav.src,
      observationQuestion: 'Perhatikan bentuk belah ketupat ini; apa yang membuat semua sisinya istimewa?',
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      aiPrompt: `TutorComic3: Bimbing siswa SD, jangan berikan jawaban langsung. Gunakan bahasa sederhana maksimal 3 kalimat. Jika jawaban benar: berikan pujian singkat, jelaskan alasan singkat, lalu ajukan satu pertanyaan lanjutan. Jika kurang tepat: jangan katakan "salah", berikan satu petunjuk observasi dan ajak menghitung sisi atau mengamati sudut. Jika siswa mengatakan "Saya tidak tahu": bimbing langkah demi langkah. Selalu hubungkan dengan gambar objek ini. -- Jelaskan ciri belah ketupat yang kamu lihat pada pola lantai.`,
      question: 'Apa ciri belah ketupat?',
      answer: 'Belah ketupat memiliki empat sisi sama panjang dan dua pasang sisi sejajar.',
      feedback: 'Bagus, kamu bisa mengenali belah ketupat dari sisi-sisinya yang sama panjang.',
      characteristics: ['Empat sisi sama panjang', 'Dua pasang sisi sejajar', 'Empat sudut', 'Bentuknya seperti wajik atau berlian'],
    },
  ],
  qrCode: [
    { id: 'komik3-qr-1', imageSrc: '/images/navigation/default.svg', alt: 'QR Persegi', label: 'Persegi', description: 'Scan untuk melihat bentuk persegi.' },
    { id: 'komik3-qr-2', imageSrc: '/images/navigation/default.svg', alt: 'QR Segitiga', label: 'Segitiga', description: 'Scan untuk melihat bentuk segitiga.' },
  ],
  model3D: [
    { id: 'komik3-model-1', title: 'Persegi', arUrl: '', page: 1, description: 'Model 3D persegi untuk pengamatan sederhana.' },
    { id: 'komik3-model-2', title: 'Segitiga', arUrl: '', page: 2, description: 'Model 3D segitiga untuk pengamatan sudut.' },
  ],
  aiPrompt: {
    navigation: 'Bantu siswa mengenali bangun datar sederhana dengan bahasa yang mudah dipahami.',
    objectTutor: 'TutorComic3: Bimbing siswa SD, jangan langsung memberi jawaban; gunakan petunjuk singkat dan bahasa sederhana; maksimal 3 kalimat; hubungkan jawaban dengan gambar objek saat ini.',
    application: 'Bantu siswa menghubungkan bangun datar dengan benda nyata di sekitar.',
    argumentation: 'Beri umpan balik sederhana tentang alasan siswa.',
    resolution: 'Bimbing siswa menyelesaikan latihan bangun datar sederhana.',
    introspection: 'Buat refleksi singkat dengan bahasa yang sederhana dan positif.',
  },
  identification: {
    questions: [
      {
        id: 'komik3-ident-1',
        question: 'Apa saja bentuk bangun datar yang kamu temukan pada Rumah Gajah Mungkur?',
        image: persegiIllustration.src,
        imageAlt: 'Ilustrasi berbagai bangun datar yang terlihat pada Rumah Gajah Mungkur.',
        options: [
          { text: 'Persegi', correct: true },
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: true },
          { text: 'Trapesium', correct: true },
          { text: 'Belah Ketupat', correct: true },
          { text: 'Lingkaran', correct: true },
        ],
        explanation: 'Pada Rumah Gajah Mungkur, kamu bisa menemukan beberapa bangun datar seperti persegi, persegi panjang, segitiga, trapesium, belah ketupat, dan lingkaran.',
      },
    ],
    feedback: {
      complete: 'Sangat bagus! Kamu berhasil mengenali bangun datar yang ada pada Rumah Gajah Mungkur.',
      partial: 'Masih ada beberapa bentuk yang perlu diperiksa lagi.',
      incomplete: 'Coba lihat kembali bagian rumah yang kamu amati dan cari bentuk yang paling cocok.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati benda di sekitar dan pilih bangun datar yang paling sesuai.',
    prompt: 'Pilih salah satu bangun datar dari daftar dan jelaskan mengapa bangun tersebut cocok untuk bagian yang kamu amati.',
    context: 'Benda-benda di sekitar Rumah Gajah Mungkur dan bagian-bagian bangunan yang terlihat di komik.',
    images: [
      { src: persegiNav.src, alt: 'Persegi', label: 'Persegi', description: 'Perhatikan sisi sama panjang dan sudut siku-siku.' },
      { src: persegiPanjangNav.src, alt: 'Persegi Panjang', label: 'Persegi Panjang', description: 'Perhatikan pasangan sisi panjang dan pendek.' },
      { src: segitigaNav.src, alt: 'Segitiga', label: 'Segitiga', description: 'Perhatikan jumlah sisi dan sudut.' },
      { src: trapesiumNav.src, alt: 'Trapesium', label: 'Trapesium', description: 'Perhatikan satu pasang sisi yang sejajar.' },
      { src: lingkaranNav.src, alt: 'Lingkaran', label: 'Lingkaran', description: 'Perhatikan bentuk melengkung dan pusatnya.' },
      { src: belahKetupatNav.src, alt: 'Belah Ketupat', label: 'Belah Ketupat', description: 'Perhatikan sisi sama panjang dan bentuk wajik.' },
    ],
    options: [
      { value: 'Persegi', label: 'Persegi' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Trapesium', label: 'Trapesium' },
      { value: 'Lingkaran', label: 'Lingkaran' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik3-arg-1',
        templePart: 'atap rumah',
        question: 'Mengapa atap rumah bisa dipahami sebagai segitiga?',
        photoSrc: AlapImg.src,
        image: AlapImg.src,
        photoAlt: 'Atap Rumah',
        shapeName: 'Segitiga',
        shapeKey: 'segitiga',
        shapeSrc: segitigaNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Atap rumah memiliki tiga sisi dan tiga sudut seperti segitiga.',
        feedback: 'Bagus! Atap memiliki bentuk yang runcing dengan tiga sisi, sehingga alasanmu sangat tepat.',
      },
      {
        id: 'komik3-arg-2',
        templePart: 'jendela rumah',
        question: 'Mengapa bentuk jendela rumah bisa dipahami sebagai persegi panjang?',
        photoSrc: JendelaImg.src,
        image: JendelaImg.src,
        photoAlt: 'Jendela Rumah',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: persegiPanjangNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Jendela memiliki empat sisi dengan dua pasang sisi yang sama panjang dan empat sudut siku-siku.',
        feedback: 'Sangat bagus! Jendela memang memiliki bentuk panjang dan lebar berbeda dengan sudut-sudut yang siku-siku.',
      },
      {
        id: 'komik3-arg-3',
        templePart: 'pintu rumah',
        question: 'Mengapa bentuk pintu rumah bisa dipahami sebagai persegi panjang?',
        photoSrc: PintuImg.src,
        image: PintuImg.src,
        photoAlt: 'Pintu Rumah',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: persegiPanjangNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Pintu rumah memiliki bentuk memanjang dengan empat sudut siku-siku dan dua pasang sisi sejajar.',
        feedback: 'Tepat! Pintu memiliki bentuk yang lebih tinggi daripada lebar, sehingga persegi panjang adalah model yang paling cocok.',
      },
      {
        id: 'komik3-arg-4',
        templePart: 'ornament pagar dengan belah ketupat',
        question: 'Mengapa ornament pagar dengan bentuk belah ketupat bisa dipahami sebagai belah ketupat?',
        photoSrc: OrnamentPagarBelahKetupatImg.src,
        image: OrnamentPagarBelahKetupatImg.src,
        photoAlt: 'Ornament Pagar Belah Ketupat',
        shapeName: 'Belah Ketupat',
        shapeKey: 'belah-ketupat',
        shapeSrc: belahKetupatNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Ornament pagar memiliki empat sisi sama panjang dan membentuk pola berlian yang khas belah ketupat.',
        feedback: 'Sempurna! Ornament ini memiliki semua sisi sama panjang dan bentuknya seperti berlian atau wajik.',
      },
      {
        id: 'komik3-arg-5',
        templePart: 'ornament pagar dengan lingkaran',
        question: 'Mengapa ornament pagar dengan bentuk bundar bisa dipahami sebagai lingkaran?',
        photoSrc: OrnamentPagarLingkaranImg.src,
        image: OrnamentPagarLingkaranImg.src,
        photoAlt: 'Ornament Pagar Lingkaran',
        shapeName: 'Lingkaran',
        shapeKey: 'lingkaran',
        shapeSrc: lingkaranNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Ornament pagar membentuk pola bundar dengan semua titik pada tepi yang sama jaraknya dari pusat.',
        feedback: 'Excellent! Ornament ini membentuk kurva tertutup yang sempurna, yaitu ciri khas lingkaran.',
      },
      {
        id: 'komik3-arg-6',
        templePart: 'atap kanopi rumah',
        question: 'Mengapa atap kanopi rumah bisa dipahami sebagai trapesium?',
        photoSrc: AtapKanopiImg.src,
        image: AtapKanopiImg.src,
        photoAlt: 'Atap Kanopi',
        shapeName: 'Trapesium',
        shapeKey: 'trapesium',
        shapeSrc: trapesiumNav.src,
        highlightColor: 'border-primary-500',
        aiContext: 'Atap kanopi memiliki dua sisi sejajar dan dua sisi yang tidak sejajar, yang merupakan ciri khas trapesium.',
        feedback: 'Bagus! Atap kanopi memiliki bentuk yang lebar di bagian atas dan lebih sempit di bawah, seperti trapesium.',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Luas Persegi',
        part: 'Bagian Depan',
        shape: 'Persegi',
        prompt: 'Sebuah persegi memiliki panjang sisi 4 cm. Berapakah luasnya?',
        options: [
          { key: 'A', label: '8 cm²' },
          { key: 'B', label: '12 cm²' },
          { key: 'C', label: '16 cm²' },
          { key: 'D', label: '20 cm²' },
        ],
        correctKey: 'C',
        answer: '16 cm²',
        formula: 'L = s × s = 4 × 4 = 16 cm²',
        explanation: 'Luas persegi dihitung dari sisi dikali sisi.',
        aiHint: 'Ingat rumus luas persegi.',
        context: 'Bentuk yang kamu lihat pada bangunan rumah.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/default.svg',
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya dapat mengenali bentuk bangun datar sederhana.',
      'Saya tahu perbedaan persegi dan segitiga.',
      'Saya lebih percaya diri mengamati benda di sekitar.',
    ],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada komik ini.',
    nextPrompt: 'Kamu bisa mengulang lagi bila ingin lebih percaya diri.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pemahamanmu terhadap bangun datar sederhana.',
    learnedShapes: ['Persegi', 'Segitiga'],
  },
};
