import persegiIllustration from '@/features/comics/comic-3/assets/navigation/persegi.svg';
import persegiPanjangIllustration from '@/features/comics/comic-3/assets/navigation/persegi-panjang.svg';
import segitigaIllustration from '@/features/comics/comic-3/assets/navigation/segitiga.svg';
import trapesiumIllustration from '@/features/comics/comic-3/assets/navigation/trapesium.svg';
import lingkaranIllustration from '@/features/comics/comic-3/assets/navigation/lingkaran.svg';

export const resolutionContent = {
  missions: [
    {
      id: 1,
      title: 'Misi 1 · Luas Persegi',
      part: 'Bagian Jendela',
      shape: 'Persegi',
      prompt: 'Sebuah jendela rumah berbentuk persegi dengan panjang sisi 6 cm. Berapakah luasnya?',
      problemData: ['Sisi = 6 cm'],
      options: [
        { key: 'A', label: '24 cm²' },
        { key: 'B', label: '30 cm²' },
        { key: 'C', label: '36 cm²' },
        { key: 'D', label: '42 cm²' },
      ],
      correctKey: 'C',
      answer: '36 cm²',
      formula: 'L = s × s',
      explanation: '6 × 6 = 36',
      hint: 'Kalikan panjang sisi dengan dirinya sendiri.',
      correctFeedback: 'Tepat! Luas persegi didapat dari sisi dikali sisi.',
      incorrectFeedback: 'Belum tepat. Periksa kembali cara menghitung luas persegi.',
      aiHint: 'Gunakan rumus luas persegi: L = s × s.',
      context: 'Persegi pada jendela rumah membantu siswa memahami luas bidang sederhana.',
      accent: 'from-primary-600 to-primary-700',
      illustration: persegiIllustration.src,
    },
    {
      id: 2,
      title: 'Misi 2 · Luas Persegi Panjang',
      part: 'Bagian Pintu',
      shape: 'Persegi Panjang',
      prompt: 'Sebuah pintu rumah berbentuk persegi panjang dengan panjang 8 cm dan lebar 5 cm. Berapakah luasnya?',
      problemData: ['Panjang = 8 cm', 'Lebar = 5 cm'],
      options: [
        { key: 'A', label: '35 cm²' },
        { key: 'B', label: '40 cm²' },
        { key: 'C', label: '45 cm²' },
        { key: 'D', label: '48 cm²' },
      ],
      correctKey: 'B',
      answer: '40 cm²',
      formula: 'L = p × l',
      explanation: '8 × 5 = 40',
      hint: 'Kalikan panjang dan lebar dengan hati-hati.',
      correctFeedback: 'Tepat! Luas persegi panjang adalah panjang dikali lebar.',
      incorrectFeedback: 'Belum tepat. Periksa kembali perkalian panjang dan lebar.',
      aiHint: 'Gunakan rumus luas persegi panjang: L = p × l.',
      context: 'Persegi panjang pada pintu rumah membantu siswa memahami luas bidang yang lebih panjang.',
      accent: 'from-secondary-500 to-secondary-600',
      illustration: persegiPanjangIllustration.src,
    },
    {
      id: 3,
      title: 'Misi 3 · Luas Segitiga',
      part: 'Bagian Atap',
      shape: 'Segitiga',
      prompt: 'Sebuah atap rumah berbentuk segitiga dengan alas 10 cm dan tinggi 6 cm. Berapakah luasnya?',
      problemData: ['Alas = 10 cm', 'Tinggi = 6 cm'],
      options: [
        { key: 'A', label: '24 cm²' },
        { key: 'B', label: '28 cm²' },
        { key: 'C', label: '30 cm²' },
        { key: 'D', label: '32 cm²' },
      ],
      correctKey: 'C',
      answer: '30 cm²',
      formula: 'L = 1/2 × a × t',
      explanation: '1/2 × 10 × 6 = 30',
      hint: 'Bagi hasil perkalian alas dan tinggi dengan 2.',
      correctFeedback: 'Tepat! Luas segitiga adalah setengah dari alas dikali tinggi.',
      incorrectFeedback: 'Belum tepat. Ingat, luas segitiga adalah setengah dari hasil alas dan tinggi.',
      aiHint: 'Gunakan rumus luas segitiga: L = 1/2 × a × t.',
      context: 'Segitiga pada atap rumah membantu siswa menghubungkan bentuk tajam dengan luasnya.',
      accent: 'from-amber-500 to-orange-500',
      illustration: segitigaIllustration.src,
    },
    {
      id: 4,
      title: 'Misi 4 · Luas Trapesium',
      part: 'Bagian Atap Kanopi',
      shape: 'Trapesium',
      prompt: 'Sebuah atap kanopi berbentuk trapesium dengan panjang sisi sejajar 8 cm dan 12 cm serta tinggi 4 cm. Berapakah luasnya?',
      problemData: ['Sisi sejajar = 8 cm dan 12 cm', 'Tinggi = 4 cm'],
      options: [
        { key: 'A', label: '36 cm²' },
        { key: 'B', label: '40 cm²' },
        { key: 'C', label: '44 cm²' },
        { key: 'D', label: '48 cm²' },
      ],
      correctKey: 'B',
      answer: '40 cm²',
      formula: 'L = 1/2 × (a + b) × t',
      explanation: '1/2 × (8 + 12) × 4 = 40',
      hint: 'Jumlahkan kedua sisi sejajar, lalu kalikan dengan tinggi lalu bagi dua.',
      correctFeedback: 'Tepat! Rumus trapesium adalah setengah dari jumlah sisi sejajar dikali tinggi.',
      incorrectFeedback: 'Belum tepat. Periksa kembali cara menjumlahkan sisi sejajar sebelum mengalikannya dengan tinggi.',
      aiHint: 'Gunakan rumus luas trapesium: L = 1/2 × (a + b) × t.',
      context: 'Trapesium pada atap kanopi memberi gambaran tentang bidang dengan dua sisi sejajar.',
      accent: 'from-emerald-500 to-emerald-600',
      illustration: trapesiumIllustration.src,
    },
    {
      id: 5,
      title: 'Misi 5 · Keliling Lingkaran',
      part: 'Bagian Ornamen Pagar',
      shape: 'Lingkaran',
      prompt: 'Sebuah ornament pagar berbentuk lingkaran dengan diameter 14 cm. Berapakah kelilingnya? (π = 22/7)',
      problemData: ['Diameter = 14 cm', 'π = 22/7'],
      options: [
        { key: 'A', label: '40 cm' },
        { key: 'B', label: '44 cm' },
        { key: 'C', label: '48 cm' },
        { key: 'D', label: '52 cm' },
      ],
      correctKey: 'B',
      answer: '44 cm',
      formula: 'K = π × d',
      explanation: '22/7 × 14 = 44',
      hint: 'Kalikan π dengan diameter.',
      correctFeedback: 'Tepat! Keliling lingkaran adalah π dikali diameter.',
      incorrectFeedback: 'Belum tepat. Ingat, keliling lingkaran menggunakan π dikali diameter.',
      aiHint: 'Gunakan rumus keliling lingkaran: K = π × d.',
      context: 'Lingkaran pada ornament pagar membantu siswa mengenali bentuk bundar dan kelilingnya.',
      accent: 'from-fuchsia-500 to-purple-600',
      illustration: lingkaranIllustration.src,
    },
  ],
};
