import type { ComicContentPackageLike } from '../../types';
import atapSegitigaSvg from '@/features/comics/comic-5/assets/identification/segitiga-atap.svg';
import jendelaPersegiPanjangSvg from '@/features/comics/comic-5/assets/identification/persegi-panjang-jendela.svg';
import rodaMeriamLingkaranSvg from '@/features/comics/comic-5/assets/identification/lingkaran-roda-meriam.svg';
import lantaiBelahKetupatSvg from '@/features/comics/comic-5/assets/identification/belah-ketupat-lantai.svg';
import segitigaIcon from '@/features/comics/comic-5/assets/identification/segitiga.svg';
import segitigaSamaKakiIcon from '@/features/comics/comic-5/assets/identification/segitiga-sama-kaki.svg';
import segitigaSamaSisiIcon from '@/features/comics/comic-5/assets/identification/segitiga-sama-sisi.svg';
import segitigaSikuSikuIcon from '@/features/comics/comic-5/assets/identification/segitiga-siku-siku.svg';
import persegiIcon from '@/features/comics/comic-5/assets/identification/persegi.svg';
import persegiPanjangIcon from '@/features/comics/comic-5/assets/identification/persegi-panjang.svg';
import trapesiumIcon from '@/features/comics/comic-5/assets/identification/trapesium.svg';
import lingkaranIcon from '@/features/comics/comic-5/assets/identification/lingkaran.svg';
import belahKetupatIcon from '@/features/comics/comic-5/assets/identification/belah-ketupat.svg';
import atapRumahApp from '@/features/comics/comic-5/assets/application/atap-rumah.svg';
import jendelaKelasApp from '@/features/comics/comic-5/assets/application/jendela-kelas.svg';
import banSepedaApp from '@/features/comics/comic-5/assets/application/ban-sepeda.svg';
import polaKeramikApp from '@/features/comics/comic-5/assets/application/pola-keramik.svg';

// Navigation assets
import atapNav from '@/features/comics/comic-5/assets/navigation/atap.svg';
import jendelaNav from '@/features/comics/comic-5/assets/navigation/jendela.svg';
import rodaMeriamNav from '@/features/comics/comic-5/assets/navigation/lingkaran.svg';
import lantaiNav from '@/features/comics/comic-5/assets/navigation/lantai.svg';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 5,
    title: 'Serunya Belajar Bangun Datar di Keraton Sumenep',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Keraton Sumenep, Madura, Jawa Timur',
    classLevel: 'II',
    cover: '/comics/komik-5/cover.png',
    thumbnail: '/comics/komik-5/thumbnail.png',
    learningTargets: [
      'Mengenal bangun datar pada benda-benda di Keraton Sumenep',
      'Mengamati bentuk atap, jendela, roda meriam, dan lantai untuk menemukan bangun datar',
      'Menghubungkan ciri bangun datar dengan objek budaya yang ada di lingkungan sekitar',
    ],
    synopsis:
      'Pak Atur dan siswa SDN Pajagalan 1 belajar bangun datar langsung di Keraton Sumenep dengan mengamati bentuk atap, jendela, roda meriam, dan lantai yang menjadi bagian dari lingkungan budaya lokal.',
  },
  learningObjects: [
    {
      id: 'komik5-atap',
      title: 'Atap',
      description: 'Atap bangunan terlihat seperti segitiga yang runcing, sama dengan bentuk segitiga yang dipelajari di komik.',
      page: 1,
      objectImage: atapSegitigaSvg.src,
      navImage: atapNav.src,
      image: atapNav.src,
      observationQuestion: 'Apa yang kamu perhatikan ketika melihat bentuk atap keraton ini? Berapa sisi dan sudutnya?',
      aiPrompt: 'Bantu siswa SD mengenali segitiga pada atap keraton. Jangan langsung beri jawaban. Gunakan petunjuk observasi dan bahasa sederhana. Hubungkan dengan gambar atap yang diperlihatkan. Maksimal 3 kalimat. Jika siswa benar, berikan pujian singkat dan ajukan satu pertanyaan lanjutan.',
      question: 'Bentuk apa yang paling cocok untuk atap keraton?',
      answer: 'Segitiga.',
      feedback: 'Benar, atap terlihat seperti segitiga karena memiliki tiga sisi dan tiga sudut.',
      characteristics: ['Tiga sisi', 'Tiga sudut', 'Bentuknya runcing ke atas', 'Simetris'],
    },
    {
      id: 'komik5-jendela',
      title: 'Jendela',
      description: 'Jendela di ruangan Keraton Sumenep tampak seperti persegi panjang dengan sisi-sisi yang berpasangan.',
      page: 2,
      objectImage: jendelaPersegiPanjangSvg.src,
      navImage: jendelaNav.src,
      image: jendelaNav.src,
      observationQuestion: 'Bagaimana bentuk jendela keraton ini? Apakah semua sisinya sama panjang?',
      aiPrompt: 'Bantu siswa SD mengenali persegi panjang pada jendela keraton. Jangan langsung beri jawaban. Ajak siswa menghitung sisi dan mengamati sudut. Gunakan bahasa sederhana. Hubungkan dengan jendela yang terlihat pada gambar. Maksimal 3 kalimat.',
      question: 'Bentuk apa yang paling cocok untuk jendela di ruangan ini?',
      answer: 'Persegi panjang.',
      feedback: 'Benar, jendela memiliki empat sisi dan empat sudut siku-siku.',
      characteristics: ['Empat sisi', 'Empat sudut siku-siku', 'Dua pasang sisi sama panjang', 'Panjang dan lebar berbeda'],
    },
    {
      id: 'komik5-roda-meriam',
      title: 'Roda Meriam',
      description: 'Roda meriam berbentuk bundar dan tampak seperti lingkaran yang mudah diamati.',
      page: 3,
      objectImage: rodaMeriamLingkaranSvg.src,
      navImage: rodaMeriamNav.src,
      image: rodaMeriamNav.src,
      observationQuestion: 'Apa yang istimewa dari bentuk roda meriam? Apakah semua bagian tepinya sama jauh dari pusat?',
      aiPrompt: 'Bantu siswa SD mengenali lingkaran pada roda meriam. Jangan langsung beri jawaban. Petunjuk: minta siswa mencari titik pusat dan mengukur jarak ke tepi. Gunakan bahasa sederhana. Hubungkan dengan roda meriam yang terlihat pada gambar. Maksimal 3 kalimat.',
      question: 'Bentuk apa yang paling cocok untuk roda meriam?',
      answer: 'Lingkaran.',
      feedback: 'Benar, roda meriam berbentuk lingkaran karena bentuknya bundar dan simetris.',
      characteristics: ['Bentuk bundar', 'Tidak memiliki sudut', 'Semua titik tepi sama jauh dari pusat', 'Satu garis lengkung tertutup'],
    },
    {
      id: 'komik5-lantai',
      title: 'Lantai',
      description: 'Motif lantai pada ruangan Keraton Sumenep tampak seperti bentuk belah ketupat.',
      page: 4,
      objectImage: lantaiBelahKetupatSvg.src,
      navImage: lantaiNav.src,
      image: lantaiNav.src,
      observationQuestion: 'Perhatikan pola lantai keraton ini; apa yang membuat semua sisinya istimewa?',
      aiPrompt: 'Bantu siswa SD mengenali belah ketupat pada pola lantai. Jangan langsung beri jawaban. Ajak siswa menghitung sisi dan mengamati bahwa semua sisi sama panjang. Gunakan bahasa sederhana. Hubungkan dengan pola lantai yang terlihat. Maksimal 3 kalimat.',
      question: 'Bentuk bangun datar apa yang paling cocok untuk pola lantai ini?',
      answer: 'Belah ketupat.',
      feedback: 'Benar, pola lantai itu mirip belah ketupat karena semua sisinya sama panjang.',
      characteristics: ['Empat sisi sama panjang', 'Dua pasang sisi sejajar', 'Empat sudut', 'Bentuknya seperti wajik atau berlian'],
    },
  ],
  qrCode: [],
  model3D: [],
  aiPrompt: {
    navigation: 'Bantu siswa mengamati bentuk pada benda budaya Keraton Sumenep dengan bahasa sederhana.',
    objectTutor: 'Bimbing siswa mengenali bentuk yang terlihat di objek budaya. Gunakan istilah sederhana dan berikan petunjuk, bukan jawaban langsung.',
    application: 'Hubungkan bangun datar dari Keraton Sumenep dengan benda lain di lingkungan sekitar siswa.',
    argumentation: 'Anda adalah guru SD yang mengevaluasi argumentasi siswa kelas II tentang bangun datar di Keraton Sumenep. Periksa apakah siswa: (1) Memahami hubungan antara objek keraton (atap, jendela, roda meriam, lantai) dengan bangun datar yang dipilih, (2) Dapat menjelaskan alasan dengan logis menggunakan bahasa sederhana, (3) Menyebutkan ciri-ciri bangun datar yang relevan (sisi, sudut, bentuk). Berikan feedback tentang kekuatan argumentasi dan area yang perlu diperbaiki. Jangan memberikan jawaban lengkap. Berikan skor 1-5 dan tentukan level: SANGAT_BAIK (skor 5), HAMPIR_BENAR (skor 3-4), atau PERLU_PERBAIKAN (skor 1-2). Gunakan respons JSON dengan field: level, score, feedback, strength, improvement, suggestion. Gunakan bahasa Indonesia yang mudah dipahami anak SD.',
    resolution: 'Bimbing siswa menyelesaikan pertanyaan tentang bangun datar yang ada pada komik dengan petunjuk singkat dan positif.',
    introspection: 'Buat refleksi singkat tentang pengalaman belajar bangun datar di Keraton Sumenep dengan bahasa yang positif dan memotivasi.',
  },
  identification: {
    questions: [
      {
        id: 'komik5-ident-1',
        question: 'Bangun datar apa saja yang kamu temukan dalam Komik Keraton Sumenep?',
        image: atapSegitigaSvg.src,
        imageAlt: 'Ilustrasi atap Keraton Sumenep yang diamati sebagai bangun datar.',
        options: [
          { text: 'Segitiga', correct: true, icon: segitigaIcon.src },
          { text: 'Segitiga Sama Kaki', correct: true, icon: segitigaSamaKakiIcon.src },
          { text: 'Segitiga Sama Sisi', correct: true, icon: segitigaSamaSisiIcon.src },
          { text: 'Segitiga Siku-Siku', correct: true, icon: segitigaSikuSikuIcon.src },
          { text: 'Persegi', correct: true, icon: persegiIcon.src },
          { text: 'Persegi Panjang', correct: true, icon: persegiPanjangIcon.src },
          { text: 'Trapesium', correct: true, icon: trapesiumIcon.src },
          { text: 'Belah Ketupat', correct: true, icon: belahKetupatIcon.src },
          { text: 'Lingkaran', correct: true, icon: lingkaranIcon.src },
        ],
        explanation: 'Pilih semua bentuk yang muncul dalam komik. Segitiga memiliki 3 sisi dan 3 sudut. Segitiga sama kaki memiliki dua sisi sama panjang, segitiga sama sisi memiliki tiga sisi sama panjang, dan segitiga siku-siku memiliki satu sudut seperti huruf L. Persegi memiliki empat sisi sama panjang, persegi panjang memiliki sisi berhadapan sama panjang, trapesium memiliki sepasang sisi sejajar, belah ketupat memiliki empat sisi sama panjang, dan lingkaran tidak memiliki titik sudut. Bentuk-bentuk itu ditemukan pada atap, gerbang, jendela, pintu kaca, roda meriam, lampu, lantai, tiang, foto figura, dan bagian bangunan Keraton Sumenep.',
      },
    ],
    feedback: {
      complete: 'Sangat bagus! Kamu berhasil mengamati dan mengenali bangun datar yang ada di Keraton Sumenep.',
      partial: 'Ada beberapa bentuk yang masih perlu diamati lebih teliti lagi.',
      incomplete: 'Coba perhatikan kembali benda-benda di komik dan cari ciri khas bangunnya.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Kehidupan Nyata',
    intro: 'Perhatikan benda-benda di sekitar rumah, sekolah, dan lingkungan budaya. Pilih bangun datar yang paling cocok untuk masing-masing benda.',
    prompt: 'Pilih bangun datar yang paling tepat untuk setiap benda dan jelaskan alasanmu dengan menghubungkan ciri bentuknya dengan aktivitas sehari-hari.',
    context: 'Dalam kehidupan sehari-hari, siswa sering melihat atap rumah, jendela kelas, ban sepeda, dan pola keramik. Bentuk-bentuk itu memuat konsep bangun datar yang sama dengan yang dipelajari di Keraton Sumenep.',
    correctAnswer: 'Segitiga',
    images: [
      { src: atapRumahApp.src, alt: 'Atap rumah berbentuk segitiga', label: 'Atap Rumah', description: 'Bentuk atap rumah mirip dengan bentuk segitiga pada bangunan keraton.' },
      { src: jendelaKelasApp.src, alt: 'Jendela kelas berbentuk persegi panjang', label: 'Jendela Kelas', description: 'Jendela kelas biasanya memiliki sisi panjang dan lebar yang berbeda, seperti persegi panjang.' },
      { src: banSepedaApp.src, alt: 'Ban sepeda berbentuk lingkaran', label: 'Ban Sepeda', description: 'Ban sepeda berputar dengan lancar karena bentuknya bundar dan tidak memiliki sudut.' },
      { src: polaKeramikApp.src, alt: 'Pola keramik berbentuk belah ketupat', label: 'Pola Keramik', description: 'Motif lantai dan keramik sering membentuk belah ketupat yang rapi dan simetris.' },
    ],
    options: [
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Lingkaran', label: 'Lingkaran' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
    cards: [
      {
        id: 'komik5-application-atap-rumah',
        title: 'Atap Rumah',
        image: atapRumahApp.src,
        description: 'Atap rumah biasanya tampak runcing seperti segitiga.',
        options: ['Segitiga', 'Persegi Panjang', 'Lingkaran'],
        correctAnswer: 'Segitiga',
        acceptableAnswers: ['Segitiga Sama Kaki', 'Segitiga Sama Sisi'],
      },
      {
        id: 'komik5-application-jendela-kelas',
        title: 'Jendela Kelas',
        image: jendelaKelasApp.src,
        description: 'Jendela kelas memiliki sisi panjang dan lebar seperti persegi panjang.',
        options: ['Persegi Panjang', 'Segitiga', 'Lingkaran'],
        correctAnswer: 'Persegi Panjang',
      },
      {
        id: 'komik5-application-ban-sepeda',
        title: 'Ban Sepeda',
        image: banSepedaApp.src,
        description: 'Ban sepeda berbentuk bundar dan tidak memiliki sudut.',
        options: ['Lingkaran', 'Segitiga', 'Belah Ketupat'],
        correctAnswer: 'Lingkaran',
      },
      {
        id: 'komik5-application-pola-keramik',
        title: 'Pola Keramik',
        image: polaKeramikApp.src,
        description: 'Pola keramik dapat membentuk wajik dengan empat sisi sama panjang.',
        options: ['Belah Ketupat', 'Persegi Panjang', 'Lingkaran'],
        correctAnswer: 'Belah Ketupat',
      },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik5-arg-1',
        title: 'Atap Keraton Sumenep',
        templePart: 'atap Keraton Sumenep',
        question: 'Menurutmu, mengapa bentuk atap Keraton Sumenep dapat dikenali sebagai segitiga?',
        photoSrc: atapSegitigaSvg.src,
        image: atapNav.src,
        photoAlt: 'Gambar atap Keraton Sumenep yang diamati sebagai segitiga.',
        shape: 'Segitiga',
        shapeName: 'Segitiga',
        shapeKey: 'segitiga',
        shapeSrc: atapNav.src,
        icon: atapSegitigaSvg.src,
        aiContext: 'Bantu siswa menghubungkan atap Keraton Sumenep dengan segitiga melalui jumlah sisi, jumlah sudut, dan bentuknya yang runcing. Jangan langsung memberi jawaban; minta siswa mengamati gambar.',
        feedback: 'Atap dapat dikenali sebagai segitiga karena memiliki tiga sisi, tiga sudut, dan bentuk yang runcing.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik5-arg-2',
        title: 'Jendela Keraton Sumenep',
        templePart: 'jendela Keraton Sumenep',
        question: 'Mengapa jendela Keraton Sumenep dapat dikaitkan dengan bentuk persegi panjang?',
        photoSrc: jendelaPersegiPanjangSvg.src,
        image: jendelaNav.src,
        photoAlt: 'Gambar jendela Keraton Sumenep yang diamati sebagai persegi panjang.',
        shape: 'Persegi Panjang',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: jendelaNav.src,
        icon: jendelaPersegiPanjangSvg.src,
        aiContext: 'Bantu siswa mengamati empat sisi, empat sudut siku-siku, sisi berhadapan yang sama panjang, serta perbedaan panjang dan lebar jendela. Jangan langsung memberi jawaban.',
        feedback: 'Jendela dapat dikaitkan dengan persegi panjang karena memiliki empat sisi, empat sudut siku-siku, dan dua pasang sisi berhadapan yang sama panjang.',
        highlightColor: 'border-secondary-500',
      },
      {
        id: 'komik5-arg-3',
        title: 'Roda Meriam Keraton Sumenep',
        templePart: 'roda meriam Keraton Sumenep',
        question: 'Mengapa roda meriam dapat dikenali sebagai lingkaran?',
        photoSrc: rodaMeriamLingkaranSvg.src,
        image: rodaMeriamNav.src,
        photoAlt: 'Gambar roda meriam Keraton Sumenep yang diamati sebagai lingkaran.',
        shape: 'Lingkaran',
        shapeName: 'Lingkaran',
        shapeKey: 'lingkaran',
        shapeSrc: rodaMeriamNav.src,
        icon: rodaMeriamLingkaranSvg.src,
        aiContext: 'Bantu siswa mengamati bahwa roda meriam berbentuk bundar, tidak memiliki sudut, memiliki satu garis lengkung tertutup, dan tepinya berjarak sama dari pusat. Jangan langsung memberi jawaban.',
        feedback: 'Roda meriam dapat dikenali sebagai lingkaran karena berbentuk bundar, tidak memiliki sudut, dan tepinya berjarak sama dari pusat.',
        highlightColor: 'border-accent-500',
      },
      {
        id: 'komik5-arg-4',
        title: 'Pola Lantai Keraton Sumenep',
        templePart: 'pola lantai Keraton Sumenep',
        question: 'Mengapa pola lantai tersebut dapat dikaitkan dengan bentuk belah ketupat?',
        photoSrc: lantaiBelahKetupatSvg.src,
        image: lantaiNav.src,
        photoAlt: 'Gambar pola lantai Keraton Sumenep yang diamati sebagai belah ketupat.',
        shape: 'Belah Ketupat',
        shapeName: 'Belah Ketupat',
        shapeKey: 'belah-ketupat',
        shapeSrc: lantaiNav.src,
        icon: lantaiBelahKetupatSvg.src,
        aiContext: 'Bantu siswa mengamati empat sisi, semua sisi sama panjang, bentuk seperti wajik atau berlian, dan empat sudut pada pola lantai. Jangan langsung memberi jawaban.',
        feedback: 'Pola lantai dapat dikaitkan dengan belah ketupat karena memiliki empat sisi yang sama panjang, empat sudut, dan bentuk seperti wajik.',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Menghitung Keliling Atap',
        part: 'Atap Keraton',
        shape: 'Segitiga',
        prompt: 'Atap keraton berbentuk segitiga dengan panjang ketiga sisi berturut-turut 6 m, 6 m, dan 8 m. Berapa keliling atap keraton itu?',
        options: [
          { key: 'A', label: '18 m' },
          { key: 'B', label: '20 m' },
          { key: 'C', label: '22 m' },
          { key: 'D', label: '24 m' },
        ],
        correctKey: 'B',
        answer: '20 m',
        formula: 'Keliling Segitiga = sisi 1 + sisi 2 + sisi 3 = 6 + 6 + 8 = 20 m',
        explanation: 'Keliling adalah jumlah semua sisi. Segitiga memiliki 3 sisi, jadi kita jumlahkan ketiga sisinya untuk mendapatkan keliling.',
        aiHint: 'Mulai dengan menulis panjang setiap sisi. Kemudian coba jumlahkan ketiga angka itu. Ingat: 6 + 6 + 8 adalah berapa?',
        context: 'Tepi atap keraton perlu dipasang hiasan. Untuk mengetahui berapa panjang hiasan yang diperlukan, kita harus menghitung keliling atap.',
        accent: 'from-primary-600 to-primary-700',
        illustration: atapSegitigaSvg.src,
      },
      {
        id: 2,
        title: 'Misi 2 · Menghitung Keliling Jendela',
        part: 'Jendela Keraton',
        shape: 'Persegi Panjang',
        prompt: 'Jendela di ruangan keraton berbentuk persegi panjang dengan panjang 3 m dan lebar 2 m. Berapa keliling jendela itu?',
        options: [
          { key: 'A', label: '8 m' },
          { key: 'B', label: '10 m' },
          { key: 'C', label: '12 m' },
          { key: 'D', label: '14 m' },
        ],
        correctKey: 'B',
        answer: '10 m',
        formula: 'Keliling Persegi Panjang = 2 × (panjang + lebar) = 2 × (3 + 2) = 2 × 5 = 10 m',
        explanation: 'Persegi panjang memiliki 2 pasang sisi yang sama panjang. Jadi kita kalikan 2 dengan jumlah panjang dan lebar.',
        aiHint: 'Bayangkan tepi jendela membentuk garis melingkar. Berapa panjang panjang jendela? Berapa panjang lebar jendela? Sekarang coba: panjang + lebar = ... Lalu kalikan dengan 2.',
        context: 'Jendela keraton akan dipasangi bingkai kayu. Untuk mengetahui panjang kayu yang diperlukan, kita perlu menghitung keliling jendela.',
        accent: 'from-amber-500 to-amber-600',
        illustration: jendelaPersegiPanjangSvg.src,
      },
      {
        id: 3,
        title: 'Misi 3 · Mengenali Lingkaran',
        part: 'Roda Meriam',
        shape: 'Lingkaran',
        prompt: 'Roda meriam di halaman keraton memiliki sifat-sifat berikut: (1) Tidak memiliki sisi yang lurus, (2) Tidak memiliki sudut, (3) Bentuknya bulat. Bangun datar apakah roda meriam itu?',
        options: [
          { key: 'A', label: 'Segitiga' },
          { key: 'B', label: 'Lingkaran' },
          { key: 'C', label: 'Persegi Panjang' },
          { key: 'D', label: 'Belah Ketupat' },
        ],
        correctKey: 'B',
        answer: 'Lingkaran',
        formula: 'Lingkaran adalah bangun datar yang terbentuk dari titik-titik yang sama jaraknya dari satu titik pusat.',
        explanation: 'Lingkaran adalah bentuk yang tidak memiliki sisi atau sudut. Semua titik di tepi lingkaran memiliki jarak yang sama ke titik pusat. Bentuknya selalu bulat, tidak peduli dari arah mana kita memandangnya.',
        aiHint: 'Pikirkan ciri-ciri lingkaran: apakah punya sisi? Apakah punya sudut? Sekarang lihat roda meriam—apakah punya sisi? Apakah punya sudut? Sama tidak dengan lingkaran?',
        context: 'Roda yang berbentuk lingkaran dapat berputar dengan mulus tanpa tersangkut sudut atau sisi yang runcing.',
        accent: 'from-cyan-500 to-cyan-600',
        illustration: rodaMeriamLingkaranSvg.src,
      },
      {
        id: 4,
        title: 'Misi 4 · Ciri-Ciri Belah Ketupat',
        part: 'Pola Lantai Keraton',
        shape: 'Belah Ketupat',
        prompt: 'Pola lantai keraton berbentuk belah ketupat. Ciri-ciri belah ketupat adalah: (1) Memiliki 4 sisi yang sama panjang, (2) Memiliki 4 sudut yang tidak semuanya 90 derajat, (3) Bentuk mirip layang-layang yang pipih. Mana pernyataan yang BENAR tentang belah ketupat?',
        options: [
          { key: 'A', label: 'Semua sudut belah ketupat adalah 90 derajat' },
          { key: 'B', label: 'Belah ketupat memiliki 4 sisi yang sama panjang' },
          { key: 'C', label: 'Belah ketupat tidak memiliki sudut' },
          { key: 'D', label: 'Belah ketupat hanya memiliki 2 sisi' },
        ],
        correctKey: 'B',
        answer: 'Belah ketupat memiliki 4 sisi yang sama panjang',
        formula: 'Keliling Belah Ketupat = 4 × sisi. Jika sisi = 5 cm, maka K = 4 × 5 = 20 cm',
        explanation: 'Belah ketupat adalah bangun datar dengan 4 sisi yang semuanya sama panjang. Perbedaannya dengan persegi adalah sudutnya tidak semuanya 90 derajat. Beberapa sudutnya lebih dari 90 derajat, beberapa kurang dari 90 derajat.',
        aiHint: 'Bandingkan: apakah semua sisi persegi sama panjang? Apakah semua sisi belah ketupat sama panjang? Jadi mana yang benar? Sekarang cek apakah semua sudut persegi 90 derajat. Apakah semua sudut belah ketupat 90 derajat? Apa perbedaannya?',
        context: 'Pola lantai keraton sering menggunakan motif belah ketupat karena bentuknya yang indah dan simetris. Setiap ruas lantai yang berbentuk belah ketupat memiliki ukuran sisi yang sama.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: lantaiBelahKetupatSvg.src,
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya dapat menjelaskan apa yang saya pelajari dari Komik 5 tentang bangun datar di Keraton Sumenep.',
      'Konsep yang paling saya pahami adalah bentuk-bentuk bangun datar yang ada pada benda di keraton.',
      'Bagian yang paling menarik dari Komik 5 adalah saat saya mengamati atap, jendela, roda meriam, dan pola lantai.',
      'Bagian yang masih sulit bagi saya adalah membedakan ciri-ciri bangun datar yang hampir mirip.',
      'Saya dapat melihat hubungan antara matematika dan budaya karena benda di Keraton Sumenep memiliki bentuk bangun datar.',
      'Saya merasa lebih siap dan lebih percaya diri saat menyelesaikan pengalaman belajar Komik 5.',
    ],
    completionMessage: 'Kamu telah menyelesaikan refleksi pembelajaran bangun datar di Keraton Sumenep dengan baik.',
    nextPrompt: 'Ayo lanjutkan dan lihat kembali benda di sekitar kita dengan rasa ingin tahu dan semangat belajar yang baru.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pengamatan siswa terhadap bangun datar di Keraton Sumenep.',
    learnedShapes: ['Segitiga', 'Persegi Panjang', 'Lingkaran', 'Belah Ketupat'],
  },
};
