import type { ComicContentPackageLike } from '../../types';
import atapSegitigaSvg from '@/features/comics/comic-5/assets/identification/segitiga-atap.svg';
import jendelaPersegiPanjangSvg from '@/features/comics/comic-5/assets/identification/persegi-panjang-jendela.svg';
import rodaMeriamLingkaranSvg from '@/features/comics/comic-5/assets/identification/lingkaran-roda-meriam.svg';
import lantaiBelahKetupatSvg from '@/features/comics/comic-5/assets/identification/belah-ketupat-lantai.svg';
import atapRumahApp from '@/features/comics/comic-5/assets/application/atap-rumah.svg';
import jendelaKelasApp from '@/features/comics/comic-5/assets/application/jendela-kelas.svg';
import banSepedaApp from '@/features/comics/comic-5/assets/application/ban-sepeda.svg';
import polaKeramikApp from '@/features/comics/comic-5/assets/application/pola-keramik.svg';

// Navigation assets
import atapNav from '@/features/comics/comic-5/assets/navigation/atap.svg';
import jendelaNav from '@/features/comics/comic-5/assets/navigation/jendela.svg';
import rodaMeriamNav from '@/features/comics/comic-5/assets/navigation/lingkaran.svg';
import lantaiNav from '@/features/comics/comic-5/assets/navigation/lantai.svg';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 5,
    title: 'Serunya Belajar Bangun Datar di Keraton Sumenep',
    subtitle: 'Etnomatematika Bangun Datar',
    location: 'Keraton Sumenep, Madura, Jawa Timur',
    classLevel: 'II',
    cover: '/comics/komik-5/cover.png',
    thumbnail: '/comics/komik-5/thumbnail.png',
    learningTargets: [
      'Mengenal bangun datar pada benda-benda di Keraton Sumenep',
      'Mengamati bentuk atap, jendela, roda meriam, dan lantai untuk menemukan bangun datar',
      'Menghubungkan ciri bangun datar dengan objek budaya yang ada di lingkungan sekitar',
    ],
    synopsis:
      'Pak Atur dan siswa SDN Pajagalan 1 belajar bangun datar langsung di Keraton Sumenep dengan mengamati bentuk atap, jendela, roda meriam, dan lantai yang menjadi bagian dari lingkungan budaya lokal.',
  },
  learningObjects: [
    {
      id: 'komik5-atap',
      title: 'Atap',
      description: 'Atap bangunan terlihat seperti segitiga yang runcing, sama dengan bentuk segitiga yang dipelajari di komik.',
      page: 1,
      qrImage: '',
      objectImage: atapSegitigaSvg.src,
      navImage: atapNav.src,
      image: atapNav.src,
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      observationQuestion: 'Apa yang kamu perhatikan ketika melihat bentuk atap keraton ini? Berapa sisi dan sudutnya?',
      aiPrompt: 'Bantu siswa SD mengenali segitiga pada atap keraton. Jangan langsung beri jawaban. Gunakan petunjuk observasi dan bahasa sederhana. Hubungkan dengan gambar atap yang diperlihatkan. Maksimal 3 kalimat. Jika siswa benar, berikan pujian singkat dan ajukan satu pertanyaan lanjutan.',
      question: 'Bentuk apa yang paling cocok untuk atap keraton?',
      answer: 'Segitiga.',
      feedback: 'Benar, atap terlihat seperti segitiga karena memiliki tiga sisi dan tiga sudut.',
      characteristics: ['Tiga sisi', 'Tiga sudut', 'Bentuknya runcing ke atas', 'Simetris'],
    },
    {
      id: 'komik5-jendela',
      title: 'Jendela',
      description: 'Jendela di ruangan Keraton Sumenep tampak seperti persegi panjang dengan sisi-sisi yang berpasangan.',
      page: 2,
      qrImage: '',
      objectImage: jendelaPersegiPanjangSvg.src,
      navImage: jendelaNav.src,
      image: jendelaNav.src,
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      observationQuestion: 'Bagaimana bentuk jendela keraton ini? Apakah semua sisinya sama panjang?',
      aiPrompt: 'Bantu siswa SD mengenali persegi panjang pada jendela keraton. Jangan langsung beri jawaban. Ajak siswa menghitung sisi dan mengamati sudut. Gunakan bahasa sederhana. Hubungkan dengan jendela yang terlihat pada gambar. Maksimal 3 kalimat.',
      question: 'Bentuk apa yang paling cocok untuk jendela di ruangan ini?',
      answer: 'Persegi panjang.',
      feedback: 'Benar, jendela memiliki empat sisi dan empat sudut siku-siku.',
      characteristics: ['Empat sisi', 'Empat sudut siku-siku', 'Dua pasang sisi sama panjang', 'Panjang dan lebar berbeda'],
    },
    {
      id: 'komik5-roda-meriam',
      title: 'Roda Meriam',
      description: 'Roda meriam berbentuk bundar dan tampak seperti lingkaran yang mudah diamati.',
      page: 3,
      qrImage: '',
      objectImage: rodaMeriamLingkaranSvg.src,
      navImage: rodaMeriamNav.src,
      image: rodaMeriamNav.src,
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      observationQuestion: 'Apa yang istimewa dari bentuk roda meriam? Apakah semua bagian tepinya sama jauh dari pusat?',
      aiPrompt: 'Bantu siswa SD mengenali lingkaran pada roda meriam. Jangan langsung beri jawaban. Petunjuk: minta siswa mencari titik pusat dan mengukur jarak ke tepi. Gunakan bahasa sederhana. Hubungkan dengan roda meriam yang terlihat pada gambar. Maksimal 3 kalimat.',
      question: 'Bentuk apa yang paling cocok untuk roda meriam?',
      answer: 'Lingkaran.',
      feedback: 'Benar, roda meriam berbentuk lingkaran karena bentuknya bundar dan simetris.',
      characteristics: ['Bentuk bundar', 'Tidak memiliki sudut', 'Semua titik tepi sama jauh dari pusat', 'Satu garis lengkung tertutup'],
    },
    {
      id: 'komik5-lantai',
      title: 'Lantai',
      description: 'Motif lantai pada ruangan Keraton Sumenep tampak seperti bentuk belah ketupat.',
      page: 4,
      qrImage: '',
      objectImage: lantaiBelahKetupatSvg.src,
      navImage: lantaiNav.src,
      image: lantaiNav.src,
      modelUrl: '',
      embedUrl: '',
      viewerType: 'embed',
      provider: '',
      observationQuestion: 'Perhatikan pola lantai keraton ini; apa yang membuat semua sisinya istimewa?',
      aiPrompt: 'Bantu siswa SD mengenali belah ketupat pada pola lantai. Jangan langsung beri jawaban. Ajak siswa menghitung sisi dan mengamati bahwa semua sisi sama panjang. Gunakan bahasa sederhana. Hubungkan dengan pola lantai yang terlihat. Maksimal 3 kalimat.',
      question: 'Bentuk bangun datar apa yang paling cocok untuk pola lantai ini?',
      answer: 'Belah ketupat.',
      feedback: 'Benar, pola lantai itu mirip belah ketupat karena semua sisinya sama panjang.',
      characteristics: ['Empat sisi sama panjang', 'Dua pasang sisi sejajar', 'Empat sudut', 'Bentuknya seperti wajik atau berlian'],
    },
  ],
  qrCode: [],
  model3D: [],
  aiPrompt: {
    navigation: 'Bantu siswa mengamati bentuk pada benda budaya Keraton Sumenep dengan bahasa sederhana.',
    objectTutor: 'Bimbing siswa mengenali bentuk yang terlihat di objek budaya. Gunakan istilah sederhana dan berikan petunjuk, bukan jawaban langsung.',
    application: 'Hubungkan bangun datar dari Keraton Sumenep dengan benda lain di lingkungan sekitar siswa.',
    argumentation: 'Anda adalah guru SD yang mengevaluasi argumentasi siswa kelas II tentang bangun datar di Keraton Sumenep. Periksa apakah siswa: (1) Memahami hubungan antara objek keraton (atap, jendela, roda meriam, lantai) dengan bangun datar yang dipilih, (2) Dapat menjelaskan alasan dengan logis menggunakan bahasa sederhana, (3) Menyebutkan ciri-ciri bangun datar yang relevan (sisi, sudut, bentuk). Berikan feedback tentang kekuatan argumentasi dan area yang perlu diperbaiki. Jangan memberikan jawaban lengkap. Berikan skor 1-5 dan tentukan level: SANGAT_BAIK (skor 5), HAMPIR_BENAR (skor 3-4), atau PERLU_PERBAIKAN (skor 1-2). Gunakan respons JSON dengan field: level, score, feedback, strength, improvement, suggestion. Gunakan bahasa Indonesia yang mudah dipahami anak SD.',
    resolution: 'Bimbing siswa menyelesaikan pertanyaan tentang bangun datar yang ada pada komik dengan petunjuk singkat dan positif.',
    introspection: 'Buat refleksi singkat tentang pengalaman belajar bangun datar di Keraton Sumenep dengan bahasa yang positif dan memotivasi.',
  },
  identification: {
    questions: [
      {
        id: 'komik5-ident-1',
        question: 'Atap bangunan Keraton Sumenep paling cocok dengan bangun datar apa?',
        image: atapSegitigaSvg.src,
        imageAlt: 'Ilustrasi atap Keraton Sumenep berbentuk segitiga.',
        options: [
          { text: 'Segitiga', correct: true },
          { text: 'Lingkaran', correct: false },
          { text: 'Persegi Panjang', correct: false },
          { text: 'Belah Ketupat', correct: false },
        ],
        explanation: 'Atap bernilai tiga sisi dan tiga sudut, sehingga bentuknya paling mirip dengan segitiga.',
      },
      {
        id: 'komik5-ident-2',
        question: 'Jendela di ruangan Keraton Sumenep paling cocok dengan bangun datar apa?',
        image: jendelaPersegiPanjangSvg.src,
        imageAlt: 'Ilustrasi jendela di ruangan Keraton Sumenep berbentuk persegi panjang.',
        options: [
          { text: 'Persegi Panjang', correct: true },
          { text: 'Segitiga', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Trapesium', correct: false },
        ],
        explanation: 'Jendela memiliki empat sisi dengan dua pasang sisi yang sama panjang dan empat sudut siku-siku, jadi bentuknya adalah persegi panjang.',
      },
      {
        id: 'komik5-ident-3',
        question: 'Benda yang Vira temukan berbentuk lingkaran adalah apa?',
        image: rodaMeriamLingkaranSvg.src,
        imageAlt: 'Ilustrasi roda meriam berbentuk lingkaran.',
        options: [
          { text: 'Roda meriam', correct: true },
          { text: 'Atap', correct: false },
          { text: 'Jendela', correct: false },
          { text: 'Lantai', correct: false },
        ],
        explanation: 'Roda meriam tampak bundar dan semua titik pada tepinya berjarak sama dari pusat, sehingga termasuk lingkaran.',
      },
      {
        id: 'komik5-ident-4',
        question: 'Motif lantai di Keraton Sumenep paling cocok dengan bangun datar apa?',
        image: lantaiBelahKetupatSvg.src,
        imageAlt: 'Ilustrasi motif lantai berbentuk belah ketupat.',
        options: [
          { text: 'Belah Ketupat', correct: true },
          { text: 'Segitiga', correct: false },
          { text: 'Lingkaran', correct: false },
          { text: 'Persegi', correct: false },
        ],
        explanation: 'Motif lantai itu memiliki empat sisi sama panjang dan bentuknya menyerupai wajik, jadi paling cocok dengan belah ketupat.',
      },
    ],
    feedback: {
      complete: 'Sangat bagus! Kamu berhasil mengamati dan mengenali bangun datar yang ada di Keraton Sumenep.',
      partial: 'Ada beberapa bentuk yang masih perlu diamati lebih teliti lagi.',
      incomplete: 'Coba perhatikan kembali benda-benda di komik dan cari ciri khas bangunnya.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Kehidupan Nyata',
    intro: 'Perhatikan benda-benda di sekitar rumah, sekolah, dan lingkungan budaya. Pilih bangun datar yang paling cocok untuk masing-masing benda.',
    prompt: 'Pilih bangun datar yang paling tepat untuk setiap benda dan jelaskan alasanmu dengan menghubungkan ciri bentuknya dengan aktivitas sehari-hari.',
    context: 'Dalam kehidupan sehari-hari, siswa sering melihat atap rumah, jendela kelas, ban sepeda, dan pola keramik. Bentuk-bentuk itu memuat konsep bangun datar yang sama dengan yang dipelajari di Keraton Sumenep.',
    images: [
      { src: atapRumahApp.src, alt: 'Atap rumah berbentuk segitiga', label: 'Atap Rumah', description: 'Bentuk atap rumah mirip dengan bentuk segitiga pada bangunan keraton.' },
      { src: jendelaKelasApp.src, alt: 'Jendela kelas berbentuk persegi panjang', label: 'Jendela Kelas', description: 'Jendela kelas biasanya memiliki sisi panjang dan lebar yang berbeda, seperti persegi panjang.' },
      { src: banSepedaApp.src, alt: 'Ban sepeda berbentuk lingkaran', label: 'Ban Sepeda', description: 'Ban sepeda berputar dengan lancar karena bentuknya bundar dan tidak memiliki sudut.' },
      { src: polaKeramikApp.src, alt: 'Pola keramik berbentuk belah ketupat', label: 'Pola Keramik', description: 'Motif lantai dan keramik sering membentuk belah ketupat yang rapi dan simetris.' },
    ],
    options: [
      { value: 'Segitiga', label: 'Segitiga' },
      { value: 'Persegi Panjang', label: 'Persegi Panjang' },
      { value: 'Lingkaran', label: 'Lingkaran' },
      { value: 'Belah Ketupat', label: 'Belah Ketupat' },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik5-arg-1',
        title: 'Bagian Atap Keraton',
        templePart: 'atap',
        question: 'Mengapa atap Keraton Sumenep dapat disebut segitiga?',
        photoSrc: atapSegitigaSvg.src,
        image: atapSegitigaSvg.src,
        photoAlt: 'Atap Keraton Sumenep berbentuk segitiga.',
        shape: 'Segitiga',
        shapeName: 'Segitiga',
        shapeKey: 'segitiga',
        shapeSrc: atapSegitigaSvg.src,
        icon: atapSegitigaSvg.src,
        aiContext: 'Bantu siswa menjelaskan mengapa atap keraton adalah segitiga. Minta siswa menghitung sisi dan sudut, lalu jelaskan bahwa bentuk runcing seperti atap biasanya adalah segitiga. Jangan langsung memberikan jawaban—berikan petunjuk observasi. Gunakan bahasa sederhana. Arahkan siswa untuk melihat ciri: 3 sisi, 3 sudut, bentuk runcing.',
        feedback: 'Bagus! Atap keraton memiliki 3 sisi dan 3 sudut, dengan bentuk yang runcing ke atas, jadi sesuai dengan segitiga.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik5-arg-2',
        title: 'Bagian Jendela Keraton',
        templePart: 'jendela',
        question: 'Mengapa jendela di ruangan keraton paling cocok disebut persegi panjang?',
        photoSrc: jendelaPersegiPanjangSvg.src,
        image: jendelaPersegiPanjangSvg.src,
        photoAlt: 'Jendela Keraton Sumenep berbentuk persegi panjang.',
        shape: 'Persegi Panjang',
        shapeName: 'Persegi Panjang',
        shapeKey: 'persegi-panjang',
        shapeSrc: jendelaPersegiPanjangSvg.src,
        icon: jendelaPersegiPanjangSvg.src,
        aiContext: 'Bantu siswa membedakan persegi panjang dengan persegi. Minta siswa mengamati dan membandingkan panjang dan lebar jendela. Tanyakan: apakah semua sisi sama panjang? Apakah ada sisi yang lebih panjang? Apakah semua sudut siku-siku? Jangan langsung beri jawaban. Arahkan untuk menemukan: 4 sisi, 4 sudut siku-siku, 2 pasang sisi sama panjang.',
        feedback: 'Bagus! Jendela keraton memiliki 4 sisi dengan 2 pasang sisi yang sama panjang, 4 sudut siku-siku, dan panjang lebih besar dari lebar, jadi cocok sebagai persegi panjang.',
        highlightColor: 'border-amber-500',
      },
      {
        id: 'komik5-arg-3',
        title: 'Bagian Roda Meriam',
        templePart: 'roda meriam',
        question: 'Mengapa roda meriam dapat dipahami sebagai lingkaran?',
        photoSrc: rodaMeriamLingkaranSvg.src,
        image: rodaMeriamLingkaranSvg.src,
        photoAlt: 'Roda meriam berbentuk lingkaran.',
        shape: 'Lingkaran',
        shapeName: 'Lingkaran',
        shapeKey: 'lingkaran',
        shapeSrc: rodaMeriamLingkaranSvg.src,
        icon: rodaMeriamLingkaranSvg.src,
        aiContext: 'Bantu siswa menemukan ciri-ciri lingkaran pada roda meriam. Minta siswa mencari titik pusat roda dan mengukur jarak dari pusat ke tepi. Tanyakan: apakah jaraknya sama? Apakah ada sisi? Apakah ada sudut? Jangan langsung beri jawaban. Arahkan untuk menemukan: bentuk bundar, tidak ada sisi, tidak ada sudut, semua titik tepi sama jauh dari pusat.',
        feedback: 'Bagus! Roda meriam berbentuk bundar dengan semua titik tepi yang sama jauh dari pusat, tidak memiliki sisi atau sudut, sehingga cocok sebagai lingkaran.',
        highlightColor: 'border-cyan-500',
      },
      {
        id: 'komik5-arg-4',
        title: 'Bagian Pola Lantai Keraton',
        templePart: 'lantai',
        question: 'Mengapa pola lantai Keraton Sumenep dapat disebut belah ketupat?',
        photoSrc: lantaiBelahKetupatSvg.src,
        image: lantaiBelahKetupatSvg.src,
        photoAlt: 'Pola lantai Keraton Sumenep berbentuk belah ketupat.',
        shape: 'Belah Ketupat',
        shapeName: 'Belah Ketupat',
        shapeKey: 'belah-ketupat',
        shapeSrc: lantaiBelahKetupatSvg.src,
        icon: lantaiBelahKetupatSvg.src,
        aiContext: 'Bantu siswa mengenali belah ketupat dari motif lantai. Minta siswa menghitung sisi dan membandingkan panjangnya dengan teliti. Tanyakan: apakah semua sisi sama panjang? Apakah ada sisi yang berbeda panjang? Apakah semua sudut 90 derajat? Bandingkan dengan persegi. Jangan langsung beri jawaban. Arahkan untuk menemukan: 4 sisi sama panjang, sudut tidak semuanya 90 derajat.',
        feedback: 'Bagus! Pola lantai memiliki 4 sisi yang sama panjang, dengan sudut yang tidak semuanya 90 derajat, sehingga cocok sebagai belah ketupat.',
        highlightColor: 'border-secondary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Menghitung Keliling Atap',
        part: 'Atap Keraton',
        shape: 'Segitiga',
        prompt: 'Atap keraton berbentuk segitiga dengan panjang ketiga sisi berturut-turut 6 m, 6 m, dan 8 m. Berapa keliling atap keraton itu?',
        options: [
          { key: 'A', label: '18 m' },
          { key: 'B', label: '20 m' },
          { key: 'C', label: '22 m' },
          { key: 'D', label: '24 m' },
        ],
        correctKey: 'B',
        answer: '20 m',
        formula: 'Keliling Segitiga = sisi 1 + sisi 2 + sisi 3 = 6 + 6 + 8 = 20 m',
        explanation: 'Keliling adalah jumlah semua sisi. Segitiga memiliki 3 sisi, jadi kita jumlahkan ketiga sisinya untuk mendapatkan keliling.',
        aiHint: 'Mulai dengan menulis panjang setiap sisi. Kemudian coba jumlahkan ketiga angka itu. Ingat: 6 + 6 + 8 adalah berapa?',
        context: 'Tepi atap keraton perlu dipasang hiasan. Untuk mengetahui berapa panjang hiasan yang diperlukan, kita harus menghitung keliling atap.',
        accent: 'from-primary-600 to-primary-700',
        illustration: atapSegitigaSvg.src,
      },
      {
        id: 2,
        title: 'Misi 2 · Menghitung Keliling Jendela',
        part: 'Jendela Keraton',
        shape: 'Persegi Panjang',
        prompt: 'Jendela di ruangan keraton berbentuk persegi panjang dengan panjang 3 m dan lebar 2 m. Berapa keliling jendela itu?',
        options: [
          { key: 'A', label: '8 m' },
          { key: 'B', label: '10 m' },
          { key: 'C', label: '12 m' },
          { key: 'D', label: '14 m' },
        ],
        correctKey: 'B',
        answer: '10 m',
        formula: 'Keliling Persegi Panjang = 2 × (panjang + lebar) = 2 × (3 + 2) = 2 × 5 = 10 m',
        explanation: 'Persegi panjang memiliki 2 pasang sisi yang sama panjang. Jadi kita kalikan 2 dengan jumlah panjang dan lebar.',
        aiHint: 'Bayangkan tepi jendela membentuk garis melingkar. Berapa panjang panjang jendela? Berapa panjang lebar jendela? Sekarang coba: panjang + lebar = ... Lalu kalikan dengan 2.',
        context: 'Jendela keraton akan dipasangi bingkai kayu. Untuk mengetahui panjang kayu yang diperlukan, kita perlu menghitung keliling jendela.',
        accent: 'from-amber-500 to-amber-600',
        illustration: jendelaPersegiPanjangSvg.src,
      },
      {
        id: 3,
        title: 'Misi 3 · Mengenali Lingkaran',
        part: 'Roda Meriam',
        shape: 'Lingkaran',
        prompt: 'Roda meriam di halaman keraton memiliki sifat-sifat berikut: (1) Tidak memiliki sisi yang lurus, (2) Tidak memiliki sudut, (3) Bentuknya bulat. Bangun datar apakah roda meriam itu?',
        options: [
          { key: 'A', label: 'Segitiga' },
          { key: 'B', label: 'Lingkaran' },
          { key: 'C', label: 'Persegi Panjang' },
          { key: 'D', label: 'Belah Ketupat' },
        ],
        correctKey: 'B',
        answer: 'Lingkaran',
        formula: 'Lingkaran adalah bangun datar yang terbentuk dari titik-titik yang sama jaraknya dari satu titik pusat.',
        explanation: 'Lingkaran adalah bentuk yang tidak memiliki sisi atau sudut. Semua titik di tepi lingkaran memiliki jarak yang sama ke titik pusat. Bentuknya selalu bulat, tidak peduli dari arah mana kita memandangnya.',
        aiHint: 'Pikirkan ciri-ciri lingkaran: apakah punya sisi? Apakah punya sudut? Sekarang lihat roda meriam—apakah punya sisi? Apakah punya sudut? Sama tidak dengan lingkaran?',
        context: 'Roda yang berbentuk lingkaran dapat berputar dengan mulus tanpa tersangkut sudut atau sisi yang runcing.',
        accent: 'from-cyan-500 to-cyan-600',
        illustration: rodaMeriamLingkaranSvg.src,
      },
      {
        id: 4,
        title: 'Misi 4 · Ciri-Ciri Belah Ketupat',
        part: 'Pola Lantai Keraton',
        shape: 'Belah Ketupat',
        prompt: 'Pola lantai keraton berbentuk belah ketupat. Ciri-ciri belah ketupat adalah: (1) Memiliki 4 sisi yang sama panjang, (2) Memiliki 4 sudut yang tidak semuanya 90 derajat, (3) Bentuk mirip layang-layang yang pipih. Mana pernyataan yang BENAR tentang belah ketupat?',
        options: [
          { key: 'A', label: 'Semua sudut belah ketupat adalah 90 derajat' },
          { key: 'B', label: 'Belah ketupat memiliki 4 sisi yang sama panjang' },
          { key: 'C', label: 'Belah ketupat tidak memiliki sudut' },
          { key: 'D', label: 'Belah ketupat hanya memiliki 2 sisi' },
        ],
        correctKey: 'B',
        answer: 'Belah ketupat memiliki 4 sisi yang sama panjang',
        formula: 'Keliling Belah Ketupat = 4 × sisi. Jika sisi = 5 cm, maka K = 4 × 5 = 20 cm',
        explanation: 'Belah ketupat adalah bangun datar dengan 4 sisi yang semuanya sama panjang. Perbedaannya dengan persegi adalah sudutnya tidak semuanya 90 derajat. Beberapa sudutnya lebih dari 90 derajat, beberapa kurang dari 90 derajat.',
        aiHint: 'Bandingkan: apakah semua sisi persegi sama panjang? Apakah semua sisi belah ketupat sama panjang? Jadi mana yang benar? Sekarang cek apakah semua sudut persegi 90 derajat. Apakah semua sudut belah ketupat 90 derajat? Apa perbedaannya?',
        context: 'Pola lantai keraton sering menggunakan motif belah ketupat karena bentuknya yang indah dan simetris. Setiap ruas lantai yang berbentuk belah ketupat memiliki ukuran sisi yang sama.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: lantaiBelahKetupatSvg.src,
      },
    ],
  },
  introspection: {
    checklist: [
      'Saya dapat menjelaskan apa yang saya pelajari dari Komik 5 tentang bangun datar di Keraton Sumenep.',
      'Konsep yang paling saya pahami adalah bentuk-bentuk bangun datar yang ada pada benda di keraton.',
      'Bagian yang paling menarik dari Komik 5 adalah saat saya mengamati atap, jendela, roda meriam, dan pola lantai.',
      'Bagian yang masih sulit bagi saya adalah membedakan ciri-ciri bangun datar yang hampir mirip.',
      'Saya dapat melihat hubungan antara matematika dan budaya karena benda di Keraton Sumenep memiliki bentuk bangun datar.',
      'Saya merasa lebih siap dan lebih percaya diri saat menyelesaikan pengalaman belajar Komik 5.',
    ],
    completionMessage: 'Kamu telah menyelesaikan refleksi pembelajaran bangun datar di Keraton Sumenep dengan baik.',
    nextPrompt: 'Ayo lanjutkan dan lihat kembali benda di sekitar kita dengan rasa ingin tahu dan semangat belajar yang baru.',
  },
  report: {
    summary: 'Laporan ini menampilkan hasil pengamatan siswa terhadap bangun datar di Keraton Sumenep.',
    learnedShapes: ['Segitiga', 'Persegi Panjang', 'Lingkaran', 'Belah Ketupat'],
  },
};
