import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 4,
    title: 'Petualangan di Jembatan Merah',
    subtitle: 'Panjang lintasan & Analisis data',
    location: 'Jembatan Merah Surabaya',
    classLevel: 'SD/MI',
    cover: '/comics/komik-4/cover.png',
    thumbnail: '/comics/komik-4/thumbnail.png',
    learningTargets: [
      'Mengukur panjang lintasan menggunakan langkah.',
      'Menghubungkan jumlah langkah dengan panjang setiap langkah.',
      'Menganalisis dan membandingkan data hasil pengukuran.',
      'Menyajikan data dalam grafik batang.',
    ],
    synopsis:
      'Dito dan teman-temannya berpetualang di Jembatan Merah Surabaya untuk belajar mengukur panjang lintasan menggunakan langkah. Mereka menemukan bahwa hasil pengukuran berbeda karena panjang langkah setiap orang berbeda, lalu menganalisis data dan menyajikannya dalam grafik batang.',
  },
  learningObjects: [],
  qrCode: [
    {
      id: 'komik4-qr-page-3',
      imageSrc: '',
      alt: 'QR AR Jembatan Merah Surabaya',
      label: 'AR Jembatan Merah Surabaya',
      type: 'AR',
      url: 'https://asblr.com/uL6tfC',
      page: 3,
      description: 'Aktifkan AR untuk melihat pengalaman interaktif Jembatan Merah Surabaya dan mengenal kisah di balik Jembatan Merah.',
    },
    {
      id: 'komik4-qr-page-14',
      imageSrc: '',
      alt: 'QR AR Hasil Pengukuran Jembatan',
      label: 'AR Hasil Pengukuran Jembatan',
      type: 'AR',
      url: 'https://asblr.com/mkyfiC',
      page: 14,
      description: 'Jelajahi AR setelah membandingkan hasil pengukuran panjang lintasan Jembatan Merah menggunakan data Hanan 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
    },
    {
      id: 'komik4-qr-page-20',
      imageSrc: '/comics/komik-4/qr/page-20.png',
      alt: 'QR Kuis Jembatan Merah',
      label: 'Kuis Jembatan Merah',
      type: 'QUIZ',
      url: 'https://app.quizwhizzer.com/play?code=35733',
      page: 20,
      description: 'Kerjakan kuis untuk menguji pemahamanmu tentang panjang lintasan, pengukuran dengan langkah, grafik batang, dan pembacaan data dalam petualangan Jembatan Merah.',
    },
  ],
  model3D: [],
  aiPrompt: {
    navigation: 'Bantu siswa mengamati pola dan bentuk sederhana dengan bahasa yang dekat dengan pengalaman mereka.',
    objectTutor: 'Jelaskan bentuk yang terlihat pada aktivitas sehari-hari.',
    application: 'Bantu siswa menghubungkan bangun datar dengan situasi baru yang familiar.',
    argumentation: 'Beri alasan singkat tentang bentuk yang dipilih.',
    resolution: 'Bimbing siswa menyelesaikan soal sederhana.',
    introspection: 'Buat refleksi singkat yang positif.',
  },
  identification: {
    questions: [
      {
        id: 'komik4-ident-1',
        question: 'Apa saja konsep matematika yang kamu temukan dalam petualangan di Jembatan Merah?',
        imageAlt: 'Ilustrasi pengukuran panjang Jembatan Merah menggunakan langkah',
        options: [
          { text: 'Pengukuran panjang lintasan', correct: true },
          { text: 'Menghitung panjang berdasarkan jumlah langkah dan panjang langkah', correct: true },
          { text: 'Menganalisis dan membandingkan data hasil pengukuran', correct: true },
          { text: 'Menyajikan data dalam grafik batang', correct: true },
          { text: 'Bangun datar', correct: false },
          { text: 'Simetri', correct: false },
        ],
        explanation: 'Benar! Dalam petualangan di Jembatan Merah, kamu belajar mengukur panjang lintasan menggunakan jumlah langkah dan panjang satu langkah, menghitung panjang lintasan, menganalisis data hasil pengukuran, serta menyajikannya dalam grafik batang.',
      },
    ],
    feedback: {
      complete: 'Benar! Dalam petualangan di Jembatan Merah, kamu belajar mengukur panjang lintasan menggunakan jumlah langkah dan panjang satu langkah, menghitung panjang lintasan, menganalisis data hasil pengukuran, serta menyajikannya dalam grafik batang.',
      partial: 'Belum tepat. Ingat kembali petualangan di Jembatan Merah. Mereka menggunakan langkah untuk mengukur panjang lintasan, menghitung panjang berdasarkan panjang langkah, membandingkan hasil pengukuran, dan menyajikan data dalam grafik.',
      incomplete: 'Belum tepat. Ingat kembali petualangan di Jembatan Merah. Mereka menggunakan langkah untuk mengukur panjang lintasan, menghitung panjang berdasarkan panjang langkah, membandingkan hasil pengukuran, dan menyajikan data dalam grafik.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Konteks Baru',
    intro: 'Amati benda yang sering kamu lihat di sekitar pasar.',
    prompt: 'Pilih bangun datar yang paling cocok dengan benda yang kamu amati.',
    context: 'Benda dan kerajinan di pasar tradisional.',
    images: [{ src: '/images/navigation/default.svg', alt: 'Bentuk persegi', label: 'Persegi', description: 'Perhatikan sisi dan sudutnya.' }],
    options: [{ value: 'Persegi', label: 'Persegi' }, { value: 'Segitiga', label: 'Segitiga' }],
  },
  argumentation: {
    questions: [
      {
        id: 'komik4-arg-1',
        templePart: 'Pengukuran Jembatan Merah',
        context: 'Hanan, Hilya, dan Aisyah mengukur Jembatan Merah dengan langkah kaki. Hanan memperoleh 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
        question: 'Menurutmu, mengapa jumlah langkah mereka berbeda meskipun mereka mengukur jembatan yang sama? Jelaskan alasanmu.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Pengukuran Jembatan Merah dengan langkah kaki',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'pengukuran-lintasan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Karena panjang langkah setiap orang berbeda. Langkah lebih panjang membutuhkan lebih sedikit langkah, sedangkan langkah lebih pendek membutuhkan lebih banyak langkah untuk lintasan yang sama.',
        expectedKeywords: ['panjang langkah', 'berbeda'],
        partialKeywords: ['langkah', 'sama'],
        explanation: 'Jumlah langkah dapat berbeda karena panjang langkah setiap orang berbeda. Orang dengan langkah lebih panjang membutuhkan lebih sedikit langkah, sedangkan orang dengan langkah lebih pendek membutuhkan lebih banyak langkah.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-2',
        templePart: 'Panjang langkah',
        context: 'Aisyah menjelaskan bahwa menghitung jumlah langkah saja belum cukup untuk mengetahui panjang Jembatan Merah.',
        question: 'Mengapa panjang langkah setiap orang perlu diukur sebelum menghitung panjang Jembatan Merah?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Mengukur panjang langkah sebelum menghitung lintasan',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'panjang-langkah',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Karena jumlah langkah harus dikaitkan dengan panjang setiap langkah untuk menghitung panjang lintasan.', value: 'A', correct: true },
          { label: 'Karena panjang jembatan berubah sesuai dengan orang yang mengukurnya.', value: 'B' },
          { label: 'Karena semua orang pasti memiliki panjang langkah yang sama.', value: 'C' },
          { label: 'Karena jumlah langkah saja sudah menunjukkan panjang jembatan secara tepat.', value: 'D' },
        ],
        expectedAnswer: 'A',
        explanation: 'Jumlah langkah saja belum cukup. Panjang langkah perlu diketahui agar dapat dikalikan dengan jumlah langkah untuk menentukan panjang lintasan.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-3',
        templePart: 'Rumus panjang lintasan',
        context: 'Bu Nisa memberikan rumus: Panjang lintasan = Jumlah langkah × Panjang langkah. Dito menempuh lintasan dengan 120 langkah dan panjang setiap langkahnya 0,75 meter.',
        question: 'Mengapa 120 × 0,75 digunakan untuk menentukan panjang lintasan Dito? Jelaskan hubungan antara jumlah langkah dan panjang setiap langkah.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perhitungan panjang lintasan dengan jumlah dan panjang langkah',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'rumus-lintasan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Setiap langkah panjangnya 0,75 meter, sehingga 120 langkah dikalikan 0,75 meter. Hasilnya 90 meter.',
        expectedKeywords: ['120', '0,75', '90'],
        partialKeywords: ['jumlah langkah', 'panjang langkah'],
        explanation: 'Setiap langkah Dito panjangnya 0,75 meter. Jadi panjang lintasannya adalah 120 × 0,75 = 90 meter.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-4',
        templePart: 'Perbedaan jumlah langkah',
        context: 'Hasil pengukuran menunjukkan Hanan 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
        question: 'Aisyah memiliki jumlah langkah paling banyak. Apakah itu berarti Aisyah berjalan di jembatan yang lebih panjang daripada Hanan dan Hilya?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perbandingan hasil pengukuran langkah',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'perbandingan-langkah',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Ya, karena jumlah langkah paling banyak berarti jembatannya paling panjang.', value: 'A' },
          { label: 'Tidak, karena mereka mengukur jembatan yang sama dan perbedaan jumlah langkah dapat disebabkan oleh perbedaan panjang langkah.', value: 'B', correct: true },
          { label: 'Ya, karena Aisyah berjalan lebih jauh daripada yang lain.', value: 'C' },
          { label: 'Tidak, karena jumlah langkah tidak dapat digunakan untuk mengukur lintasan.', value: 'D' },
        ],
        expectedAnswer: 'B',
        explanation: 'Mereka mengukur jembatan yang sama. Perbedaan jumlah langkah dapat disebabkan oleh perbedaan panjang langkah setiap orang.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-5',
        templePart: 'Grafik batang hasil pengukuran',
        context: 'Bu Nisa meminta siswa menyajikan hasil pengukuran Hanan, Hilya, dan Aisyah dalam grafik batang.',
        question: 'Mengapa grafik batang cocok digunakan untuk menyajikan data jumlah langkah mereka?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Penyajian data pengukuran dalam grafik batang',
        shapeName: 'Grafik batang',
        shapeKey: 'grafik-batang',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Karena grafik batang membantu membandingkan jumlah langkah dengan lebih mudah.', value: 'A', correct: true },
          { label: 'Karena grafik batang membuat jumlah langkah menjadi sama.', value: 'B' },
          { label: 'Karena grafik batang digunakan untuk menghitung panjang langkah.', value: 'C' },
          { label: 'Karena grafik batang dapat mengubah jumlah langkah menjadi meter secara otomatis.', value: 'D' },
        ],
        expectedAnswer: 'A',
        explanation: 'Grafik batang membantu melihat dan membandingkan perbedaan jumlah langkah secara visual.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-6',
        templePart: 'Data kendaraan di Jembatan Merah',
        context: 'Data kendaraan yang melewati Jembatan Merah adalah sepeda motor 18.450, mobil 6.230, angkutan umum 890, dan truk/bus 310. Totalnya 25.880 kendaraan.',
        question: 'Bagaimana kamu dapat menentukan kendaraan yang paling banyak dan paling sedikit hanya dari data tersebut? Jelaskan alasanmu.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Data jumlah kendaraan yang melewati Jembatan Merah',
        shapeName: 'Membandingkan data',
        shapeKey: 'data-kendaraan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Bandingkan jumlah setiap jenis kendaraan. Sepeda motor paling banyak dengan 18.450, sedangkan truk/bus paling sedikit dengan 310.',
        expectedKeywords: ['18.450', '310'],
        partialKeywords: ['sepeda motor', 'truk'],
        explanation: 'Dengan membandingkan semua angka, sepeda motor memiliki jumlah terbesar, 18.450, dan truk/bus memiliki jumlah terkecil, 310.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-7',
        templePart: 'Perbandingan data kendaraan',
        context: 'Sepeda motor berjumlah 18.450 kendaraan, sedangkan truk/bus hanya 310 kendaraan.',
        question: 'Apa yang dapat kamu simpulkan dari perbedaan kedua data tersebut? Jelaskan berdasarkan angka yang tersedia.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perbandingan jumlah sepeda motor dan truk bus',
        shapeName: 'Membandingkan data',
        shapeKey: 'kesimpulan-data',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Sepeda motor jauh lebih banyak melewati Jembatan Merah daripada truk/bus karena jumlahnya 18.450, sedangkan truk/bus hanya 310.',
        expectedKeywords: ['18.450', '310'],
        partialKeywords: ['sepeda motor', 'lebih banyak'],
        explanation: 'Sepeda motor jauh lebih banyak daripada truk/bus. Kesimpulan itu didukung oleh angka 18.450 dan 310.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-8',
        templePart: 'Manfaat membaca data',
        context: 'Bu Nisa mengatakan bahwa data dapat membantu kita memahami keadaan di sekitar.',
        question: 'Menurutmu, mengapa membaca dan membandingkan data penting dalam kehidupan sehari-hari? Gunakan contoh dari data kendaraan di Jembatan Merah.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Membaca dan membandingkan data kendaraan',
        shapeName: 'Membaca data',
        shapeKey: 'manfaat-data',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Data membantu mengetahui keadaan berdasarkan informasi nyata. Contohnya, sepeda motor paling banyak dan truk/bus paling sedikit melewati Jembatan Merah.',
        expectedKeywords: ['data', 'sepeda motor', 'truk'],
        partialKeywords: ['membandingkan', 'kendaraan'],
        explanation: 'Data membantu kita memahami keadaan berdasarkan informasi nyata. Dari data ini, sepeda motor paling banyak dan truk/bus paling sedikit melewati Jembatan Merah.',
        highlightColor: 'border-primary-500',
      },
    ],
  },
  resolution: {
    missions: [{ id: 1, title: 'Misi 1 · Luas Persegi', part: 'Susunan Keramik', shape: 'Persegi', prompt: 'Sebuah persegi memiliki panjang sisi 5 cm. Berapakah luasnya?', options: [{ key: 'A', label: '20 cm²' }, { key: 'B', label: '25 cm²' }, { key: 'C', label: '30 cm²' }], correctKey: 'B', answer: '25 cm²', formula: 'L = s × s = 5 × 5 = 25 cm²', explanation: 'Luas persegi dihitung dari sisi dikali sisi.', aiHint: 'Ingat rumus luas persegi.', context: 'Bentuk pada susunan keramik.', accent: 'from-primary-600 to-primary-700', illustration: '/images/navigation/default.svg' }],
  },
  introspection: {
    checklist: ['Saya mengenali bentuk persegi di lingkungan sekitar.', 'Saya lebih percaya diri mengamati pola sederhana.'],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada komik ini.',
    nextPrompt: 'Kamu bisa mengulang lagi bila ingin lebih percaya diri.',
  },
  report: { summary: 'Laporan sederhana untuk pembelajaran bentuk di pasar.', learnedShapes: ['Persegi'] },
};
