import type { ComicContentPackageLike } from '../../types';

export const packageContent: ComicContentPackageLike = {
  metadata: {
    comicId: 4,
    title: 'Petualangan di Jembatan Merah',
    subtitle: 'Panjang lintasan & Analisis data',
    location: 'Jembatan Merah Surabaya',
    classLevel: 'SD/MI',
    cover: '/comics/komik-4/cover.png',
    thumbnail: '/comics/komik-4/thumbnail.png',
    learningTargets: [
      'Mengukur panjang lintasan menggunakan langkah.',
      'Menghubungkan jumlah langkah dengan panjang setiap langkah.',
      'Menganalisis dan membandingkan data hasil pengukuran.',
      'Menyajikan data dalam grafik batang.',
    ],
    synopsis:
      'Dito dan teman-temannya berpetualang di Jembatan Merah Surabaya untuk belajar mengukur panjang lintasan menggunakan langkah. Mereka menemukan bahwa hasil pengukuran berbeda karena panjang langkah setiap orang berbeda, lalu menganalisis data dan menyajikannya dalam grafik batang.',
  },
  learningObjects: [],
  qrCode: [
    {
      id: 'komik4-qr-page-3',
      imageSrc: '',
      alt: 'QR AR Jembatan Merah Surabaya',
      label: 'AR Jembatan Merah Surabaya',
      type: 'AR',
      url: 'https://asblr.com/uL6tfC',
      page: 3,
      description: 'Aktifkan AR untuk melihat pengalaman interaktif Jembatan Merah Surabaya dan mengenal kisah di balik Jembatan Merah.',
    },
    {
      id: 'komik4-qr-page-14',
      imageSrc: '',
      alt: 'QR AR Hasil Pengukuran Jembatan',
      label: 'AR Hasil Pengukuran Jembatan',
      type: 'AR',
      url: 'https://asblr.com/mkyfiC',
      page: 14,
      description: 'Jelajahi AR setelah membandingkan hasil pengukuran panjang lintasan Jembatan Merah menggunakan data Hanan 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
    },
    {
      id: 'komik4-qr-page-20',
      imageSrc: '/comics/komik-4/qr/page-20.png',
      alt: 'QR Kuis Jembatan Merah',
      label: 'Kuis Jembatan Merah',
      type: 'QUIZ',
      url: 'https://app.quizwhizzer.com/play?code=35733',
      page: 20,
      description: 'Kerjakan kuis untuk menguji pemahamanmu tentang panjang lintasan, pengukuran dengan langkah, grafik batang, dan pembacaan data dalam petualangan Jembatan Merah.',
    },
  ],
  model3D: [],
  aiPrompt: {
    navigation: 'Bantu siswa mengamati pola dan bentuk sederhana dengan bahasa yang dekat dengan pengalaman mereka.',
    objectTutor: 'Jelaskan bentuk yang terlihat pada aktivitas sehari-hari.',
    application: 'Bantu siswa menghubungkan bangun datar dengan situasi baru yang familiar.',
    argumentation: 'Beri alasan singkat tentang bentuk yang dipilih.',
    resolution: 'Bimbing siswa menyelesaikan soal sederhana.',
    introspection: 'Buat refleksi singkat yang positif.',
  },
  identification: {
    questions: [
      {
        id: 'komik4-ident-1',
        question: 'Apa saja konsep matematika yang kamu temukan dalam petualangan di Jembatan Merah?',
        imageAlt: 'Ilustrasi pengukuran panjang Jembatan Merah menggunakan langkah',
        options: [
          { text: 'Pengukuran panjang lintasan', correct: true },
          { text: 'Menghitung panjang berdasarkan jumlah langkah dan panjang langkah', correct: true },
          { text: 'Menganalisis dan membandingkan data hasil pengukuran', correct: true },
          { text: 'Menyajikan data dalam grafik batang', correct: true },
          { text: 'Bangun datar', correct: false },
          { text: 'Simetri', correct: false },
        ],
        explanation: 'Benar! Dalam petualangan di Jembatan Merah, kamu belajar mengukur panjang lintasan menggunakan jumlah langkah dan panjang satu langkah, menghitung panjang lintasan, menganalisis data hasil pengukuran, serta menyajikannya dalam grafik batang.',
      },
    ],
    feedback: {
      complete: 'Benar! Dalam petualangan di Jembatan Merah, kamu belajar mengukur panjang lintasan menggunakan jumlah langkah dan panjang satu langkah, menghitung panjang lintasan, menganalisis data hasil pengukuran, serta menyajikannya dalam grafik batang.',
      partial: 'Belum tepat. Ingat kembali petualangan di Jembatan Merah. Mereka menggunakan langkah untuk mengukur panjang lintasan, menghitung panjang berdasarkan panjang langkah, membandingkan hasil pengukuran, dan menyajikan data dalam grafik.',
      incomplete: 'Belum tepat. Ingat kembali petualangan di Jembatan Merah. Mereka menggunakan langkah untuk mengukur panjang lintasan, menghitung panjang berdasarkan panjang langkah, membandingkan hasil pengukuran, dan menyajikan data dalam grafik.',
    },
  },
  application: {
    title: 'Terapkan Ilmu di Jembatan Merah',
    intro: 'Gunakan langkah, rumus panjang lintasan, dan data kendaraan untuk memecahkan situasi baru yang masih berkaitan dengan Jembatan Merah.',
    prompt: 'Pilih jawaban yang tepat untuk setiap situasi baru, lalu jelaskan alasanmu menggunakan data dan konsep dari Komik 4.',
    context: 'Situasi baru tentang pengukuran jarak dengan langkah kaki, perbandingan hasil pengukuran, dan data kendaraan di Jembatan Merah.',
    images: [
      { src: '/comics/komik-4/cover.png', alt: 'Jembatan Merah Surabaya', label: 'Konteks Jembatan Merah', description: 'Terapkan cara mengukur panjang lintasan dan membaca data yang dipelajari dari komik.' },
    ],
    options: [
      { value: '28,8 meter', label: '28,8 meter' },
      { value: '32 meter', label: '32 meter' },
      { value: 'Hasilnya sama karena jaraknya sama', label: 'Hasilnya sama karena jaraknya sama' },
      { value: 'Hasil dapat berbeda karena panjang langkah berbeda', label: 'Hasil dapat berbeda karena panjang langkah berbeda' },
      { value: 'Sepeda motor paling banyak', label: 'Sepeda motor paling banyak' },
      { value: 'Truk/bus besar paling sedikit', label: 'Truk/bus besar paling sedikit' },
    ],
    cards: [
      {
        id: 'komik4-application-lintasan',
        title: 'Situasi 1 · Mengukur Halaman',
        image: '/comics/komik-4/cover.png',
        description: 'Raka mengukur halaman sekolah dengan 48 langkah. Panjang satu langkahnya 0,6 meter. Berapa panjang halaman itu?',
        options: ['28,8 meter', '32 meter', 'Hasilnya sama karena jaraknya sama'],
        correctAnswer: '28,8 meter',
      },
      {
        id: 'komik4-application-perbandingan',
        title: 'Situasi 2 · Membandingkan Pengukuran',
        image: '/comics/komik-4/cover.png',
        description: 'Raka mendapat 48 langkah dan Sinta mendapat 40 langkah untuk jarak yang sama. Mengapa hasil langkah mereka berbeda?',
        options: ['Hasilnya sama karena jaraknya sama', 'Hasil dapat berbeda karena panjang langkah berbeda', '28,8 meter'],
        correctAnswer: 'Hasil dapat berbeda karena panjang langkah berbeda',
      },
      {
        id: 'komik4-application-kendaraan',
        title: 'Situasi 3 · Membaca Data Kendaraan',
        image: '/comics/komik-4/cover.png',
        description: 'Data di Jembatan Merah mencatat sepeda motor 18.450 kendaraan dan truk/bus besar 310 kendaraan. Kesimpulan yang tepat adalah...',
        options: ['Sepeda motor paling banyak', 'Truk/bus besar paling sedikit', '28,8 meter'],
        correctAnswer: 'Sepeda motor paling banyak',
      },
    ],
  },
  argumentation: {
    questions: [
      {
        id: 'komik4-arg-1',
        templePart: 'Pengukuran Jembatan Merah',
        context: 'Hanan, Hilya, dan Aisyah mengukur Jembatan Merah dengan langkah kaki. Hanan memperoleh 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
        question: 'Menurutmu, mengapa jumlah langkah mereka berbeda meskipun mereka mengukur jembatan yang sama? Jelaskan alasanmu.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Pengukuran Jembatan Merah dengan langkah kaki',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'pengukuran-lintasan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Karena panjang langkah setiap orang berbeda. Langkah lebih panjang membutuhkan lebih sedikit langkah, sedangkan langkah lebih pendek membutuhkan lebih banyak langkah untuk lintasan yang sama.',
        expectedKeywords: ['panjang langkah', 'berbeda'],
        partialKeywords: ['langkah', 'sama'],
        explanation: 'Jumlah langkah dapat berbeda karena panjang langkah setiap orang berbeda. Orang dengan langkah lebih panjang membutuhkan lebih sedikit langkah, sedangkan orang dengan langkah lebih pendek membutuhkan lebih banyak langkah.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-2',
        templePart: 'Panjang langkah',
        context: 'Aisyah menjelaskan bahwa menghitung jumlah langkah saja belum cukup untuk mengetahui panjang Jembatan Merah.',
        question: 'Mengapa panjang langkah setiap orang perlu diukur sebelum menghitung panjang Jembatan Merah?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Mengukur panjang langkah sebelum menghitung lintasan',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'panjang-langkah',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Karena jumlah langkah harus dikaitkan dengan panjang setiap langkah untuk menghitung panjang lintasan.', value: 'A', correct: true },
          { label: 'Karena panjang jembatan berubah sesuai dengan orang yang mengukurnya.', value: 'B' },
          { label: 'Karena semua orang pasti memiliki panjang langkah yang sama.', value: 'C' },
          { label: 'Karena jumlah langkah saja sudah menunjukkan panjang jembatan secara tepat.', value: 'D' },
        ],
        expectedAnswer: 'A',
        explanation: 'Jumlah langkah saja belum cukup. Panjang langkah perlu diketahui agar dapat dikalikan dengan jumlah langkah untuk menentukan panjang lintasan.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-3',
        templePart: 'Rumus panjang lintasan',
        context: 'Bu Nisa memberikan rumus: Panjang lintasan = Jumlah langkah × Panjang langkah. Dito menempuh lintasan dengan 120 langkah dan panjang setiap langkahnya 0,75 meter.',
        question: 'Mengapa 120 × 0,75 digunakan untuk menentukan panjang lintasan Dito? Jelaskan hubungan antara jumlah langkah dan panjang setiap langkah.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perhitungan panjang lintasan dengan jumlah dan panjang langkah',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'rumus-lintasan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Setiap langkah panjangnya 0,75 meter, sehingga 120 langkah dikalikan 0,75 meter. Hasilnya 90 meter.',
        expectedKeywords: ['120', '0,75', '90'],
        partialKeywords: ['jumlah langkah', 'panjang langkah'],
        explanation: 'Setiap langkah Dito panjangnya 0,75 meter. Jadi panjang lintasannya adalah 120 × 0,75 = 90 meter.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-4',
        templePart: 'Perbedaan jumlah langkah',
        context: 'Hasil pengukuran menunjukkan Hanan 60 langkah, Hilya 76 langkah, dan Aisyah 83 langkah.',
        question: 'Aisyah memiliki jumlah langkah paling banyak. Apakah itu berarti Aisyah berjalan di jembatan yang lebih panjang daripada Hanan dan Hilya?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perbandingan hasil pengukuran langkah',
        shapeName: 'Pengukuran panjang lintasan',
        shapeKey: 'perbandingan-langkah',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Ya, karena jumlah langkah paling banyak berarti jembatannya paling panjang.', value: 'A' },
          { label: 'Tidak, karena mereka mengukur jembatan yang sama dan perbedaan jumlah langkah dapat disebabkan oleh perbedaan panjang langkah.', value: 'B', correct: true },
          { label: 'Ya, karena Aisyah berjalan lebih jauh daripada yang lain.', value: 'C' },
          { label: 'Tidak, karena jumlah langkah tidak dapat digunakan untuk mengukur lintasan.', value: 'D' },
        ],
        expectedAnswer: 'B',
        explanation: 'Mereka mengukur jembatan yang sama. Perbedaan jumlah langkah dapat disebabkan oleh perbedaan panjang langkah setiap orang.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-5',
        templePart: 'Grafik batang hasil pengukuran',
        context: 'Bu Nisa meminta siswa menyajikan hasil pengukuran Hanan, Hilya, dan Aisyah dalam grafik batang.',
        question: 'Mengapa grafik batang cocok digunakan untuk menyajikan data jumlah langkah mereka?',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Penyajian data pengukuran dalam grafik batang',
        shapeName: 'Grafik batang',
        shapeKey: 'grafik-batang',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'choice',
        options: [
          { label: 'Karena grafik batang membantu membandingkan jumlah langkah dengan lebih mudah.', value: 'A', correct: true },
          { label: 'Karena grafik batang membuat jumlah langkah menjadi sama.', value: 'B' },
          { label: 'Karena grafik batang digunakan untuk menghitung panjang langkah.', value: 'C' },
          { label: 'Karena grafik batang dapat mengubah jumlah langkah menjadi meter secara otomatis.', value: 'D' },
        ],
        expectedAnswer: 'A',
        explanation: 'Grafik batang membantu melihat dan membandingkan perbedaan jumlah langkah secara visual.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-6',
        templePart: 'Data kendaraan di Jembatan Merah',
        context: 'Data kendaraan yang melewati Jembatan Merah adalah sepeda motor 18.450, mobil 6.230, angkutan umum 890, dan truk/bus 310. Totalnya 25.880 kendaraan.',
        question: 'Bagaimana kamu dapat menentukan kendaraan yang paling banyak dan paling sedikit hanya dari data tersebut? Jelaskan alasanmu.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Data jumlah kendaraan yang melewati Jembatan Merah',
        shapeName: 'Membandingkan data',
        shapeKey: 'data-kendaraan',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Bandingkan jumlah setiap jenis kendaraan. Sepeda motor paling banyak dengan 18.450, sedangkan truk/bus paling sedikit dengan 310.',
        expectedKeywords: ['18.450', '310'],
        partialKeywords: ['sepeda motor', 'truk'],
        explanation: 'Dengan membandingkan semua angka, sepeda motor memiliki jumlah terbesar, 18.450, dan truk/bus memiliki jumlah terkecil, 310.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-7',
        templePart: 'Perbandingan data kendaraan',
        context: 'Sepeda motor berjumlah 18.450 kendaraan, sedangkan truk/bus hanya 310 kendaraan.',
        question: 'Apa yang dapat kamu simpulkan dari perbedaan kedua data tersebut? Jelaskan berdasarkan angka yang tersedia.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Perbandingan jumlah sepeda motor dan truk bus',
        shapeName: 'Membandingkan data',
        shapeKey: 'kesimpulan-data',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Sepeda motor jauh lebih banyak melewati Jembatan Merah daripada truk/bus karena jumlahnya 18.450, sedangkan truk/bus hanya 310.',
        expectedKeywords: ['18.450', '310'],
        partialKeywords: ['sepeda motor', 'lebih banyak'],
        explanation: 'Sepeda motor jauh lebih banyak daripada truk/bus. Kesimpulan itu didukung oleh angka 18.450 dan 310.',
        highlightColor: 'border-primary-500',
      },
      {
        id: 'komik4-arg-8',
        templePart: 'Manfaat membaca data',
        context: 'Bu Nisa mengatakan bahwa data dapat membantu kita memahami keadaan di sekitar.',
        question: 'Menurutmu, mengapa membaca dan membandingkan data penting dalam kehidupan sehari-hari? Gunakan contoh dari data kendaraan di Jembatan Merah.',
        photoSrc: '/comics/komik-4/cover.png',
        photoAlt: 'Membaca dan membandingkan data kendaraan',
        shapeName: 'Membaca data',
        shapeKey: 'manfaat-data',
        shapeSrc: '/comics/komik-4/cover.png',
        answerType: 'text',
        expectedAnswer: 'Data membantu mengetahui keadaan berdasarkan informasi nyata. Contohnya, sepeda motor paling banyak dan truk/bus paling sedikit melewati Jembatan Merah.',
        expectedKeywords: ['data', 'sepeda motor', 'truk'],
        partialKeywords: ['membandingkan', 'kendaraan'],
        explanation: 'Data membantu kita memahami keadaan berdasarkan informasi nyata. Dari data ini, sepeda motor paling banyak dan truk/bus paling sedikit melewati Jembatan Merah.',
        highlightColor: 'border-primary-500',
      },
    ],
  },
  resolution: {
    missions: [
      {
        id: 1,
        title: 'Misi 1 · Perbedaan Langkah',
        part: 'Pengukuran Jembatan Merah',
        shape: 'Panjang lintasan',
        prompt: 'Mengapa jumlah langkah Hanan, Hilya, dan Aisyah berbeda saat mengukur Jembatan Merah yang sama? Perhatikan perbedaan panjang langkah mereka.',
        options: [
          { key: 'A', label: 'Karena panjang langkah setiap anak berbeda.' },
          { key: 'B', label: 'Karena panjang Jembatan Merah berubah-ubah.' },
          { key: 'C', label: 'Karena jumlah langkah tidak dapat digunakan untuk mengukur lintasan.' },
          { key: 'D', label: 'Karena semua anak berjalan di jembatan yang berbeda.' },
        ],
        correctKey: 'A',
        answer: 'Jumlah langkah berbeda karena panjang langkah setiap anak berbeda.',
        formula: 'Panjang lintasan = jumlah langkah × panjang langkah',
        explanation: 'Mereka mengukur lintasan yang sama. Anak dengan langkah lebih panjang membutuhkan lebih sedikit langkah, sedangkan langkah lebih pendek membutuhkan lebih banyak langkah.',
        aiHint: 'Bandingkan panjang langkah setiap anak, bukan panjang jembatannya.',
        context: 'Hanan, Hilya, dan Aisyah mengukur Jembatan Merah dengan langkah kaki.',
        accent: 'from-primary-600 to-primary-700',
        illustration: '/images/navigation/default.svg',
      },
      {
        id: 2,
        title: 'Misi 2 · Membandingkan Langkah',
        part: 'Data pengukuran',
        shape: 'Jumlah langkah',
        prompt: 'Data pengukuran menunjukkan Hanan 83 langkah, Hilya 76 langkah, dan Aisyah 60 langkah. Siapa yang menggunakan langkah paling banyak?',
        options: [
          { key: 'A', label: 'Hanan, yaitu 83 langkah.' },
          { key: 'B', label: 'Hilya, yaitu 76 langkah.' },
          { key: 'C', label: 'Aisyah, yaitu 60 langkah.' },
          { key: 'D', label: 'Ketiganya sama banyak.' },
        ],
        correctKey: 'A',
        answer: 'Hanan menggunakan 83 langkah, jumlah paling banyak.',
        formula: '83 > 76 > 60',
        explanation: 'Dengan membandingkan ketiga angka, 83 adalah jumlah terbesar. Jadi Hanan menggunakan langkah paling banyak.',
        aiHint: 'Bandingkan angka 83, 76, dan 60 dari yang terbesar.',
        context: 'Hasil pengukuran langkah kaki di Jembatan Merah.',
        accent: 'from-secondary-500 to-secondary-600',
        illustration: '/images/navigation/default.svg',
      },
      {
        id: 3,
        title: 'Misi 3 · Rumus Panjang Lintasan',
        part: 'Perhitungan lintasan',
        shape: 'Panjang lintasan',
        prompt: 'Hilya menempuh 76 langkah. Jika panjang setiap langkah Hilya 0,75 meter, berapa panjang lintasannya?',
        options: [
          { key: 'A', label: '56 meter' },
          { key: 'B', label: '57 meter' },
          { key: 'C', label: '57,75 meter' },
          { key: 'D', label: '76,75 meter' },
        ],
        correctKey: 'B',
        answer: '57 meter',
        formula: 'Panjang lintasan = 76 × 0,75 = 57 meter',
        explanation: 'Gunakan rumus panjang lintasan = jumlah langkah × panjang langkah. Jadi 76 × 0,75 = 57 meter.',
        aiHint: 'Kalikan jumlah langkah dengan panjang satu langkah.',
        context: 'Rumus pengukuran panjang lintasan pada Jembatan Merah.',
        accent: 'from-amber-500 to-orange-500',
        illustration: '/images/navigation/default.svg',
      },
      {
        id: 4,
        title: 'Misi 4 · Kendaraan Terbanyak',
        part: 'Grafik kendaraan',
        shape: 'Membandingkan data',
        prompt: 'Data kendaraan di Jembatan Merah adalah sepeda motor 18.450, mobil pribadi 6.230, angkutan umum 890, dan truk/bus besar 310. Kendaraan apa yang paling banyak?',
        options: [
          { key: 'A', label: 'Sepeda motor, 18.450 kendaraan.' },
          { key: 'B', label: 'Mobil pribadi, 6.230 kendaraan.' },
          { key: 'C', label: 'Angkutan umum, 890 kendaraan.' },
          { key: 'D', label: 'Truk/bus besar, 310 kendaraan.' },
        ],
        correctKey: 'A',
        answer: 'Sepeda motor, yaitu 18.450 kendaraan.',
        formula: '18.450 > 6.230 > 890 > 310',
        explanation: 'Sepeda motor memiliki angka paling besar, yaitu 18.450 kendaraan.',
        aiHint: 'Cari angka terbesar pada data kendaraan.',
        context: 'Data kendaraan yang melewati Jembatan Merah.',
        accent: 'from-emerald-500 to-emerald-600',
        illustration: '/images/navigation/default.svg',
      },
      {
        id: 5,
        title: 'Misi 5 · Kendaraan Tersedikit',
        part: 'Grafik kendaraan',
        shape: 'Membandingkan data',
        prompt: 'Dari data kendaraan di Jembatan Merah, kendaraan apa yang jumlahnya paling sedikit?',
        options: [
          { key: 'A', label: 'Sepeda motor, 18.450 kendaraan.' },
          { key: 'B', label: 'Mobil pribadi, 6.230 kendaraan.' },
          { key: 'C', label: 'Angkutan umum, 890 kendaraan.' },
          { key: 'D', label: 'Truk/bus besar, 310 kendaraan.' },
        ],
        correctKey: 'D',
        answer: 'Truk/bus besar, yaitu 310 kendaraan.',
        formula: '310 < 890 < 6.230 < 18.450',
        explanation: 'Truk/bus besar memiliki angka paling kecil, yaitu 310 kendaraan.',
        aiHint: 'Cari angka terkecil pada data kendaraan.',
        context: 'Data kendaraan yang melewati Jembatan Merah.',
        accent: 'from-sky-500 to-sky-600',
        illustration: '/images/navigation/default.svg',
      },
    ],
  },
  introspection: {
    checklist: ['Saya mengenali bentuk persegi di lingkungan sekitar.', 'Saya lebih percaya diri mengamati pola sederhana.'],
    completionMessage: 'Kamu telah menyelesaikan pembelajaran pada komik ini.',
    nextPrompt: 'Kamu bisa mengulang lagi bila ingin lebih percaya diri.',
  },
  report: { summary: 'Laporan sederhana untuk pembelajaran bentuk di pasar.', learnedShapes: ['Persegi'] },
};
